refactor(query): redefine feature count and pop a message when limit …
infra-geo-ouverte/igo2-lib pull request #1055
Opened 2022-05-18 16:09 UTC by PhilippeLafreniere18

…is exceeded

**Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
When query features exceed the feature count, nothing is triggered to the user
Default feature count is set to 5

**What is the new behavior?**
When query features exceed the feature count, an info message is displayed
Default feature count is set to 20

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [X] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**

**Other information**:

2022-05-18 20:50 UTC, pelord requested changes
I propose to change the message to something like that.. 
You have queried this layer. It's possible to have some remaining feature on the map. Zoom on map to ensure to have access to all features... Something like that (and better i hope)

2022-05-19 15:27 UTC, pelord approved these changes
Approved if the message is changed.

2022-05-20 19:12 UTC, PhilippeLafreniere18 commented
@pelord ready to be tested again

2022-06-08 18:03 UTC, pelord approved these changes

2022-06-08 18:04 UTC, merged