feat(draw): Management of the editing of the labels
infra-geo-ouverte/igo2-lib pull request #1059
Opened 2022-05-19 14:58 UTC by kalvinkhuu

**Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)

[Link to the issue](https://github.com/infra-geo-ouverte/igo2/issues/773)

**What is the new behavior?**

1. Added a cancel button with its respective logic
2. Allowing the user to double click the selected drawing to edit its label
3. User can now edit the font size and style of the labels of their drawings

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [X] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**

**Other information**:

2022-06-02 20:28 UTC, PhilippeLafreniere18 requested changes
I think the form-field for font type and size is a little bit big in the igo2 display. Maybe minimize it a bit and place them side by side ?

2022-06-07 19:44 UTC, PhilippeLafreniere18 requested changes

2022-06-07 19:44 UTC, PhilippeLafreniere18 commented on packages/geo/src/lib/draw/draw/draw.component.html
> +        </mat-icon>
Can stay on the same line (as before)

2022-06-07 19:44 UTC, PhilippeLafreniere18 commented on packages/geo/src/lib/draw/draw/draw.component.html
> +
delete line

2022-06-07 19:44 UTC, PhilippeLafreniere18 commented on packages/geo/src/lib/draw/draw/draw.component.html
> +        />
Can stay on the same line (as before). Remove "/"

2022-06-07 19:44 UTC, PhilippeLafreniere18 commented on packages/geo/src/lib/draw/draw/draw.component.html
> +              <img src="{{ icon }}" />
Remove "/"

2022-06-07 19:44 UTC, PhilippeLafreniere18 commented on packages/geo/src/lib/draw/draw/draw.component.html
> +            >{{ 'igo.geo.draw.noIcon' | translate }}
Can stay on the same line (as before)

2022-06-07 19:44 UTC, PhilippeLafreniere18 commented on packages/geo/src/lib/draw/draw/draw.component.html
> +              <img src="{{ icon_html }}" />
Remove "/"

2022-06-10 13:09 UTC, pelord commented
@PhilippeLafreniere18  1.12 is the target?

2022-06-10 13:16 UTC, pelord approved these changes

2022-06-10 13:18 UTC, merged