Drawing coordinate label
infra-geo-ouverte/igo2-lib pull request #1092
Opened 2022-08-11 15:53 UTC by kalvinkhuu

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
[Link to the issue](https://github.com/infra-geo-ouverte/igo2/issues/663)

**What is the new behavior?**
1. User can add coordinates, length and area values as the label with respective units
2. User can now press the pencil icon to edit the drawing's label
3. UI redesign on the popup dialog

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**

**Other information**:
This branch is based off the branch [DessinPlusieursCouches2.0](https://github.com/infra-geo-ouverte/igo2-lib/tree/DessinPlusieurCouches2.0). After the PR of that branch is pushed through, the changes should not be as big as it is initially.

2022-11-21 15:56 UTC, pelord requested changes
allow area and perimeters for polygon? (check box?)
when you edit a polygon with label.. his current label type is not checked.

2022-11-28 19:50 UTC, PhilippeLafreniere18 commented
> allow area and perimeters for polygon? (check box?) when you edit a polygon with label.. his current label type is not checked.

Fix

2022-11-28 21:15 UTC, pelord requested changes
1-more digits on coordinates
2- translate A: for polygon area,

2022-11-30 14:55 UTC, pelord approved these changes

2022-11-30 14:56 UTC, merged