feat(geo): save search results in layer
infra-geo-ouverte/igo2-lib pull request #1179
Opened 2023-02-01 13:57 UTC by aziz-access

**What is the current behavior?** (You can also link to an open issue here)
This update relate to the issue [896](https://github.com/infra-geo-ouverte/igo2/issues/896) in igo2.

**What is the new behavior?**
Save search results to an existing or a new layer.

2023-02-14 13:50 UTC, PhilippeLafreniere18 requested changes
Without testing, just a few minor comments

2023-02-14 13:50 UTC, PhilippeLafreniere18 commented on packages/geo/src/lib/search/search-results/search-results-add-button.component.ts
> +      layer.id.includes('igo-saved-layer')
I think "igo-search-layer" would be more meaningful

2023-02-14 13:50 UTC, PhilippeLafreniere18 commented on packages/geo/src/locale/en.geo.json
> +        "feature.addToLayar": "Add to Layar",
Same as above (change to search section, remove 'feature.')

2023-02-14 13:53 UTC, aziz-access commented on packages/geo/src/lib/search/search-results/search-results-add-button.component.ts
> +    'igo.geo.catalog.feature.addToLayar'
ok

2023-02-14 13:53 UTC, aziz-access commented on packages/geo/src/lib/search/search-results/save-feature-dialog.component.html
> +          placeholder="{{'igo.geo.layer.pleaseChooseOrSet' | translate}}"
ok

2023-02-23 19:49 UTC, PhilippeLafreniere18 approved these changes

2023-02-23 19:49 UTC, PhilippeLafreniere18 commented on packages/geo/src/lib/search/search-results/search-results-add-button.component.ts
> +    'igo.geo.search.addToLayar'
typo -> addToLayer

2023-02-23 19:49 UTC, PhilippeLafreniere18 commented on packages/geo/src/locale/en.geo.json
> +        "addToLayar": "Add to Layar",
typo -> addToLayer

2023-02-23 19:49 UTC, PhilippeLafreniere18 commented on packages/geo/src/locale/fr.geo.json
> +        "addToLayar": "Ajouter à une couche",
typo -> addToLayer

2023-02-23 21:05 UTC, PhilippeLafreniere18 requested changes
Two problems here : 
- I hit the following error when adding a new search feature to an existing search layer
![image](https://user-images.githubusercontent.com/53181414/221029761-e522bc14-ad48-4cee-80f8-b6491e3a8af0.png)
 - It seems to have a problem with z index criteria. Layer list should be sorted by z index, but when adding search layer, weird behavior is happening
 
![image](https://user-images.githubusercontent.com/53181414/221029998-4a65e5b1-f115-4128-8efb-edb8efc7443e.png)
![image](https://user-images.githubusercontent.com/53181414/221030079-9da09752-084d-4eb2-a2f9-a81f19c524a2.png)

2023-03-09 15:48 UTC, PhilippeLafreniere18 approved these changes

2023-03-15 14:44 UTC, merged