feat(ilayer/catalog): add visible/non-visible badge icon
infra-geo-ouverte/igo2-lib pull request #1184
Opened 2023-02-20 17:07 UTC by PhilippeLafreniere18

**Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
When a search result layer or a catalog item layer is added to the map, there is no badge to indicate the state of the layer

**What is the new behavior?**
An eye/eye-off logic is implemented to allow the user to see whether or not the layer added to the map is visible

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [X] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**

**Other information**:

2023-03-03 15:58 UTC, pelord requested changes
see comments.

2023-03-03 15:58 UTC, pelord commented on packages/geo/src/locale/fr.geo.json
> +        "layer.removeFromMapNotVisible": "Retirer de la carte. La donnée est visible à l'échelle active, mais n'est pas activée. Veuillez basculer vers l'outil carte pour jouer sur sa visibilité.",
remplacer jouer pour "rendre la couche visible"?

2023-03-03 15:58 UTC, pelord commented on packages/geo/src/locale/fr.geo.json
> +        "layer.removeFromMapVisible": "Retirer de la carte. La donnée est déjà visible à l'échelle active. Veuillez basculer vers l'outil carte pour jouer sur sa visibilité.",
Plus global, j'enleverais ce state...
![image](https://user-images.githubusercontent.com/7397743/222766822-e89cd287-2046-4f1c-bf26-e017cc619c69.png)

La poubelle joue déja ce role.

2023-03-03 15:58 UTC, pelord commented on packages/geo/src/locale/en.geo.json
> +        "layer.removeFromMapVisible": "Remove from map. The layer is visible at the current scale. Toggle the map tool to adjust layer visibility.",
Globally, I would remove this state...
![image](https://user-images.githubusercontent.com/7397743/222766822-e89cd287-2046-4f1c-bf26-e017cc619c69.png)

The trash can already plays this role.

2023-03-03 15:59 UTC, pelord commented on packages/geo/src/locale/fr.geo.json
> +        "layer.removeFromMapVisible": "Retirer de la carte. La donnée est déjà visible à l'échelle active. Veuillez basculer vers l'outil carte pour jouer sur sa visibilité.",
En fait, pas juste le tooltip, vraiment le state au complet.

2023-03-03 18:38 UTC, PhilippeLafreniere18 commented on packages/geo/src/locale/fr.geo.json
> +        "layer.removeFromMapNotVisible": "Retirer de la carte. La donnée est visible à l'échelle active, mais n'est pas activée. Veuillez basculer vers l'outil carte pour jouer sur sa visibilité.",
Mais non ! On joue avec la couche ! C'est comme un jouet pour les géomaticiens :P

2023-03-14 14:26 UTC, pelord approved these changes

2023-03-14 14:27 UTC, merged