fix(geo): solve absence of legend when printing an image
infra-geo-ouverte/igo2-lib pull request #1191
Opened 2023-03-03 21:58 UTC by aziz-access

**What is the current behavior?** (You can also link to an open issue here)

this update relate to the issue [678](https://github.com/infra-geo-ouverte/igo2/issues/678)  of igo2

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [ ] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**

**Other information**:

2023-03-09 16:01 UTC, PhilippeLafreniere18 approved these changes

2023-03-09 16:01 UTC, PhilippeLafreniere18 commented on packages/geo/src/lib/print/print/print.component.ts
> +          data.doZipFile,
remove ,

2023-03-09 16:01 UTC, PhilippeLafreniere18 commented on packages/geo/src/lib/print/print-form/print-form.component.ts
> +    if(data.legendPosition === 'newpage') {
Add for every legend position

2023-03-09 16:02 UTC, PhilippeLafreniere18 requested changes

2023-03-09 16:02 UTC, PhilippeLafreniere18 commented on packages/geo/src/lib/print/print-form/print-form.component.ts
> +    if(data.legendPosition === 'newpage') {
Add for every legend position

2023-03-10 16:40 UTC, PhilippeLafreniere18 requested changes
There is two problems i've seen.

1- When the legend is added on a new page, It is only the legend that is printed with the image (all formats does that).

2- Not directly link to this specific issue, but title, subtitle, comments, projection and scale aren't printed with all image formats except for JPEG who works fine.

2023-03-14 12:28 UTC, PhilippeLafreniere18 requested changes
Change translation when adding the legend on a new image (instead of page)

2023-03-14 18:53 UTC, PhilippeLafreniere18 approved these changes

2023-03-15 14:01 UTC, pelord commented
https://github.com/infra-geo-ouverte/igo2/issues/913 into the next version.

2023-03-15 14:01 UTC, merged