Button default options
infra-geo-ouverte/igo2-lib pull request #1246
Opened 2023-05-09 18:29 UTC by ThierryNormand

New button used to select the default options for the search results.

Can revert all options back to default or only revert specified group.

Button next to Select All button.

2024-01-18 14:15 UTC, pelord requested changes

2024-01-18 14:15 UTC, pelord commented on packages/geo/src/locale/fr.geo.json
> +          "defaultSettings": "Sélection par défaut",
P-etre trouver un titre de bouton plus explicite. M^me chose en anglais svp.

2024-02-01 18:50 UTC, alecarn commented on packages/geo/src/lib/search/search-settings/search-settings.component.scss
> +.checkMenuDefaultButton {
Habituellement, on utilise le kebab-case pour les classes/propriété en CSS.

2024-02-01 20:01 UTC, alecarn requested changes
1. Pour le UI, je trouve que le bouton n'a pas sa place dans un menu ou il n'y a aucune sélection de disponible ou de visible. 
![image](https://github.com/infra-geo-ouverte/igo2-lib/assets/133774929/c58850fe-8481-4cab-b934-f2a9c058e1ab)
2. Est-ce que ce serait intéressant d'utiliser un [master checkbox](https://material.angular.io/components/table/examples#table-selection) qui permet de tout cocher/décocher et indique un état intermédiaire lorsque ce n'est pas le cas? 
Par exemple:
![image](https://github.com/infra-geo-ouverte/igo2-lib/assets/133774929/c991c1e8-06a3-48db-a3e6-c13fa58bc016)
3.  On pourrait p-t améliorer l'intégration du bouton "Sélection par défaut" en utilisant un bouton icone?
![image](https://github.com/infra-geo-ouverte/igo2-lib/assets/133774929/f108fd37-b102-4127-be7d-077ae9311d1e)


Sinon une non-conformité, le menu sort de l'écran
![image](https://github.com/infra-geo-ouverte/igo2-lib/assets/133774929/d1bb2628-f98a-4182-b765-aa955974ae4c)

2024-02-02 14:51 UTC, pelord commented on packages/geo/src/lib/search/search-settings/search-settings.component.ts
> +        setting.values.map((value, index) => {
C'est drole, je venais lui dire l'inverse dans un autre pr.. Je ne suis pas sur de bien comprendre la justification

2024-04-02 18:46 UTC, ThierryNormand commented on packages/geo/src/lib/search/search-settings/search-settings.component.scss
> +  padding: 0 5px;
Je me base sur des éléments déjà existants comme le bouton de tout sélectionner qui utilise ce multiple

2024-04-02 18:48 UTC, ThierryNormand commented on packages/geo/src/lib/search/shared/sources/icherche.ts
> +      ? Number(this.options.params.limit)
Nous avons ces extensions. Le formattage se fait selon ces extensions. Une erreur de formattage a pu se glisser ici.

2024-04-05 14:30 UTC, ThierryNormand commented on packages/geo/src/lib/search/search-settings/search-settings.component.scss
>  .checkAllButton {
Corrigé

2024-04-05 14:32 UTC, ThierryNormand commented on packages/geo/src/lib/search/search-settings/search-settings.component.ts
> +    event,
Corrigé, PointerEvent

2024-04-05 14:35 UTC, ThierryNormand commented on packages/geo/src/lib/search/search-settings/search-settings.component.ts
> +    setting.allEnabled = true;
Sinon, ça crée un état où le bouton de sélection par défaut sélectionnait tout lorsque tout était désélectionné.

2024-04-05 14:40 UTC, ThierryNormand commented on packages/geo/src/lib/search/shared/sources/icherche.ts
> +      !forceReset && this.options.params && this.options.params.limit
C'est pour le bouton qui remet tous les dépendances par défaut. Ce bouton n'a pas les settings dans son container. Sans le forceReset, les valeurs par défaut des radio button changeaient selon l'option sélectionnée.

2024-04-05 14:42 UTC, ThierryNormand commented on packages/geo/src/lib/search/search-settings/search-settings.component.ts
> +    this.checkUncheckAll(event, source, setting);
Dépendamment de la valeur du bouton de tout sélectionner, un état faisait que le bouton de sélection par défaut ne fonctionnait pas. Ça "reset" en quelque sorte.

2025-01-29 18:08 UTC, alecarn commented on packages/geo/src/lib/search/shared/sources/cadastre.ts
> +  getDefaultOptions(): SearchSourceOptions {
Pourquoi enlever le protected?

2025-01-29 18:08 UTC, alecarn commented on packages/geo/src/lib/search/search-settings/search-settings.component.scss
> +  padding: 0 5px;
Je crois qu'il faut se conformer ici

2025-01-29 18:10 UTC, alecarn requested changes
Faudrait faire le tour des commentaire et on a des erreurs de typage

2025-01-29 18:10 UTC, alecarn commented on packages/geo/src/lib/search/shared/sources/icherche.ts
> +  getDefaultOptions(forceReset?: Boolean): SearchSourceOptions {
Erreur de typage

2025-04-08 20:31 UTC, pelord commented
remplacé par https://github.com/infra-geo-ouverte/igo2-lib/pull/1754

2025-04-08 20:31 UTC, closed without merging