feat(SearchBar): add a way to invalidate the cache on setting change
infra-geo-ouverte/igo2-lib pull request #1262
Opened 2023-05-24 15:47 UTC by alecarn

infra-geo-ouverte/igo2#928

**Please check if the PR fulfills these requirements**
- [x ] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
https://github.com/infra-geo-ouverte/igo2/issues/928

**What is the new behavior?**
A new property to configure the SearchBar and invalidate the cache après un changement de paramètre `bustCacheOnSettingChange`

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**

**Other information**:

2023-06-15 17:19 UTC, pelord commented
@alecarn Does the custom cache buster must be implemented for other search sources (reverse TerrApi, iLayers...?)

2023-06-15 17:40 UTC, alecarn commented
Yes we need to change our approach for these sources. If you accept this PR, I will create another ticket to apply this solution to the problem.

2023-09-08 15:39 UTC, alecarn commented
@pelord, I applied the same logic to other problematic cached query. It's ready for a second review and I will appreciate if you can test.

2023-09-12 21:17 UTC, pelord requested changes

2023-09-12 21:17 UTC, pelord commented on packages/geo/src/lib/search/shared/sources/cadastre.ts
There is no need to handle custom cache on cadadastre source because there is no options related.
But I think we should keep it as suggested in your PR.

2023-09-13 13:12 UTC, merged