feat(ogcFilters): add multiple selection for autocomplete with chips
infra-geo-ouverte/igo2-lib pull request #1274
Opened 2023-05-31 18:25 UTC by matt-litwiller

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
Single selection autocomplete
No checkboxes
No chips

**What is the new behavior?**
Multiple selection autocomplete
Added checkboxes for options
Added chips

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**

**Other information**:
![image](https://github.com/infra-geo-ouverte/igo2-lib/assets/132291945/6c924436-94b6-4650-9d79-4a3fd6457971)

2023-12-20 19:20 UTC, LAMM26 commented
Should be good to go

2023-12-20 19:22 UTC, LAMM26 approved these changes

2024-01-24 16:43 UTC, alecarn commented
@LAMM26 Pourrais-tu nous donner des instructions sur comment tester cette PR?

2024-01-24 16:58 UTC, LAMM26 commented
> @LAMM26 Pourrais-tu nous donner des instructions sur comment tester cette PR?

Dans l'assemblage igo2, il est possible de tester avec le contexte des filtres attributaires -> couche radars photos. Le dernier filtre est de type autocomplete et il devrait être possible de tester la sélection multiple.

2024-01-24 19:08 UTC, alecarn commented
@LAMM26 Pourrais-tu corriger les tests qui échoue dans le [Pipeline](https://github.com/infra-geo-ouverte/igo2-lib/actions/runs/7279853954/job/19837028175?pr=1274)

2024-01-26 14:48 UTC, alecarn requested changes

2024-01-26 14:48 UTC, alecarn commented on packages/geo/src/lib/filter/ogc-filter-chips/ogc-filter-chips.component.html
> +<div *ngIf="size <= thresholdSize" class="selected-options">
Est-ce qu'on devrait utiliser les composantes de Angular, par exemple les Chips?
On a un exemple [d'autocomplete avec chips](https://material.angular.io/components/chips/overview#chips-autocomplete). On pourrait p-t enlever le concept de `thresholdSize` si la composante d'Angular est bien fait

Je n'ai pas été en mesure de tester, lorsque je sélectionne deux éléments rien ne s'affiche et le controller du formulaire indique qu'il est invalide
![image](https://github.com/infra-geo-ouverte/igo2-lib/assets/133774929/46a16923-e873-4801-8eb3-806168773d7c)

2024-01-26 14:48 UTC, alecarn commented on packages/geo/src/lib/filter/ogc-filter-selection/ogc-filter-selection.component.html
> +              </mat-autocomplete>
C'est un chantier à part entière mais on aurait pu utiliser des concepts de compositions pour isoler la logique de l'autocomplete dans une composante, ex: `OgcFilterAutocompleteSelection`. Cela aurait faciliter le code review et la maintenance dans le future.
On pourrait p-t analyser si ça vaudrait la peine d'ajouter de la composition et ouvrir une tâche en conséquence.

2024-01-26 14:48 UTC, alecarn commented on packages/geo/src/lib/filter/ogc-filter-selection/ogc-filter-selection.component.html
> +                *ngFor="let ogcAutocomplete of filteredOgcAutocomplete[bundle.id] | async">
Est-ce que ce tag `div` est utile? 
Si non, on pourrait l'enlever et mettre le ngFor directement au niveau du `mat-option`

2024-01-26 14:48 UTC, alecarn commented on packages/geo/src/lib/filter/ogc-filter-selection/ogc-filter-selection.component.html
> +                        [disabled]="true"
Lorsque les options sont affichés elle semble être dans un état disabled.
![image](https://github.com/infra-geo-ouverte/igo2-lib/assets/133774929/60fccaef-d74f-4018-91ad-4055216f4003)

2024-05-10 20:11 UTC, LAMM26 commented on packages/geo/src/lib/filter/ogc-filter-selection/ogc-filter-selection.component.html
> +              </mat-autocomplete>
Oui ça pourrait être une piste de refactor majeur pour les filtres. Même chose pour les checkboxes, radiobuttons, select, etc.

2024-05-14 13:06 UTC, alecarn commented
@LAMM26 Je n'ai pas été en mesure de tester, la sélection multiple ne s'affiche pas et dans la console on retrouve des erreurs
![image](https://github.com/infra-geo-ouverte/igo2-lib/assets/133774929/05140fd5-e5a1-4e8f-afbe-e85ff4da3ad6)

2024-05-15 13:46 UTC, alecarn commented
Ça ne semble pas fonctionner:

https://github.com/infra-geo-ouverte/igo2-lib/assets/133774929/f6b4f1ae-e3d6-4d54-96f7-2d4bb331140c

2024-05-31 15:13 UTC, alecarn requested changes
Il y a aussi un problème de flickering dans le menu de sélection
https://github.com/infra-geo-ouverte/igo2-lib/assets/133774929/ea858ba1-51ec-4446-ac6d-dffa5358413a

2024-05-31 15:13 UTC, alecarn commented on packages/geo/src/lib/filter/ogc-filter-selection/ogc-filter-selection.component.ts
>                    .toLowerCase()
J'obtiens des erreurs, pour reproduire:

1. Aller dans les filtres de la couche
2. Sélectionner au moins un filtre
3. Cliquer sur le bouton Retour en arrière pour quitter le panneau de filtre
4. Retourner dans les filtres de la couche
![image](https://github.com/infra-geo-ouverte/igo2-lib/assets/133774929/de58c24e-bfb4-4f9a-9f97-5772bc0661d5)

2024-05-31 19:28 UTC, LAMM26 commented on packages/geo/src/lib/filter/shared/ogc-filter.interface.ts
> +  unfilterButton?: boolean;
Pas dramatique pour le moment, je vais remettre à 'unfiltered', c'est juste que le nom de la config était pas très clair.

2024-05-31 19:52 UTC, LAMM26 commented on packages/geo/src/lib/filter/ogc-filter-selection/ogc-filter-selection.component.ts
>                    .toLowerCase()
Pour le flickering c'est vraiment tannant parce que le matAutocomplete est fait pour être refermé automatiquement après une sélection. Je vais essayé d'améliorer la technique pour éviter que ça flicker

2024-06-03 14:16 UTC, alecarn commented on packages/geo/src/lib/filter/ogc-filter-selection/ogc-filter-selection.component.ts
>                    .toLowerCase()
Il va rester cette erreur à corrigé

2024-06-03 20:49 UTC, alecarn approved these changes
Ça semble être fonctionnel.
Il y a certain élément au niveau de la configuration qui me semble mystérieux mais c'est du legacy...

2024-06-05 16:05 UTC, merged

2024-06-05 16:13 UTC, alecarn commented
:tada: This PR is included in version 17.0.0-next.12 :tada:

The release is available on:
- `v17.0.0-next.12`
- [GitHub release](https://github.com/infra-geo-ouverte/igo2-lib/releases/tag/v17.0.0-next.12)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-08-22 16:21 UTC, alecarn commented
:tada: This PR is included in version 17.0.0 :tada:

The release is available on:
- `v17.0.0`
- [GitHub release](https://github.com/infra-geo-ouverte/igo2-lib/releases/tag/v17.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: