Catalog service list generator
infra-geo-ouverte/igo2-lib pull request #1282
Opened 2023-06-09 14:52 UTC by ThierryNormand

Create a button to generate the list of layers used in the catalogs of the application. 
Loop through the catalogs and determine the context of the layer. 
Automatically creates and download a .CSV file for the user.

2023-10-19 16:16 UTC, pelord requested changes

2023-10-19 16:16 UTC, pelord commented on packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.ts
> +        'rang Catalog',
trouver un moyen de rendre ca générique et applicable a tous les partenaires igo

2023-10-19 16:16 UTC, pelord commented on packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.ts
> +          .subscribe((contextLayers) => {
Trouver une facon de ne pas avoir de "nested" subscribe. Tu devrais avoir 1 seul subscribe et gerer avec un switchmap ou concatmap (ou autre ;)

2023-10-19 16:16 UTC, pelord commented on packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.ts
> +                      contextLayersList.push(layerContextList.title);
Je ne comprends pas l'utilisé de ceci.

2023-10-19 16:16 UTC, pelord commented on packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.ts
> +            link.setAttribute('download', 'liste_couches.csv');
nom générique anglais francais (basé sur une traduction probablement)

2023-10-19 16:16 UTC, pelord commented on packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.ts
> +                var gestionnaire = 'MTQ';
Voir une autre facon de gérer le gestionnaire + mettre en anglais.

2023-10-19 16:16 UTC, pelord commented on packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.ts
> +                var gestionnaire = 'MTQ';
Voir une autre facon de gérer le gestionnaire + mettre en anglais.

2024-01-18 18:32 UTC, pelord commented on packages/integration/src/locale/en.integration.json
> +          "url": "URL (Intranet/Internet)",
supprimer intranet/internet svp

2024-01-18 18:32 UTC, pelord commented on packages/integration/src/locale/en.integration.json
> +          "documentName": "catalogList.csv"
p-etre mettre une date dans le nom du fichier?

2024-01-18 18:32 UTC, pelord commented on packages/integration/src/locale/en.integration.json
> +          "documentName": "catalogList.csv"
+ heure?

2024-01-18 18:32 UTC, pelord commented on packages/integration/src/locale/fr.integration.json
> +          "documentName": "listeCatalogue.csv"
ListeCouchesInformation_date_heure.csv?

2024-01-18 19:06 UTC, pelord requested changes

2024-01-18 19:06 UTC, pelord commented on packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.ts
> +  private getDescription(item: any) {
peux tu changer le any par un autre type?

2024-01-18 19:06 UTC, pelord commented on packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.ts
> +    zip([
peut etre assigner dans une subscription et le unsuscribe on destry de la component.

2024-01-24 14:06 UTC, pelord commented on packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.ts
> +    zip([
ex: 

```
...
this.generateList$$ = zip([...
...
=======================
ngOnDestroy() {
    if (this.generatelist$$) {
        this.generatelist$$.unsubscribe();
    }
}
```

2024-02-05 16:16 UTC, alecarn requested changes

2024-02-05 16:16 UTC, alecarn commented on packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.ts
> +    this.generatelist$$ = zip([
Pourquoi utiliser le `zip` versus un `forkJoin`ou un `combineLatest`? J'ai toujours utilisé les deux derniers et selon la doc:
![image](https://github.com/infra-geo-ouverte/igo2-lib/assets/133774929/1e2a037d-ba5b-4f97-ba77-9b99a086c5e6)

2024-02-05 16:16 UTC, alecarn commented on packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.ts
> +  getCatalogList(): void {
Commentaire générale sur cette méthode, la règle du pouce c'est qu'une méthode qui fait plus de 100 lignes de codes pourrait être décortiqué pour améliorer la lisibilité. On retrouve des console.log et un TODO, on pourrait faire un ménage et améliorer la lisibilité pour les prochains développeurs qui passeront par ici.

2024-02-05 16:16 UTC, alecarn commented on packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.ts
> +        returnv: [
Pourquoi le `returnv`?

2024-02-05 16:24 UTC, alecarn commented on packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.ts
> +    ]).subscribe(
Par rapport à mon commentaire sur la lisibilité et de décortiquer cette méthode... Par exemple, on pourrait isoler ce bout de code dans un méthode `getAllContexts` qui permettrait aux développeurs de comprendre rapidement ce que ça fait sans s'embourber sur le comment et la même logique pourrait être appliquer à d'autre section de cette méthode.
```suggestion
    this.getAllContexts().subscribe(
```

2024-02-06 16:36 UTC, pelord commented on packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.ts
> +    }
Non car au moment de faire cet appel, ce ne sont pas tous des layers de créés, c'est simplement des potentiel layers qui pourraient etre crée. L,idée en soi est excellente mais pas applicable dans ce cas.

2024-02-06 16:44 UTC, pelord commented on packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.ts
> +    }
Je vais déplacer cette méthode dans le fichier any-datasource.utils.ts (nouveau fichier)

2024-02-06 17:37 UTC, pelord commented
@alecarn ready pour un autre review ;)

2024-02-07 21:49 UTC, alecarn requested changes
Deuxième round de revue terminé

2024-02-07 21:49 UTC, alecarn commented on packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.ts
> +        return `${e.rank}${sep}${e.layerTitle}${sep}${e.layerGroup}${sep}${e.catalog}${sep}${e.provider}${sep}${e.url}${sep}${e.layerName}${sep}${e.context}${sep}${e.dataDescription}`;
Pourquoi ne pas afficher le id?
Si le id est toujours en premier et qu'on ne veut pas l'afficher, on pourrait simplifier:
```suggestion
        return Object.values(e).shift().join(sep);
```

2024-02-07 21:49 UTC, alecarn commented on packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.ts
> +    document.body.removeChild(exportDocument);
Est-ce qu'on pourrait utiliser nos utilitaires par exemple `@igo2/utils/files.ts#downloadContent`

2024-02-07 21:49 UTC, alecarn commented on packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.ts
> +        .getLocalContexts()
Pourquoi qu'on jumêle les contextes avec les catalogues?

2024-02-07 21:49 UTC, alecarn commented on packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.html
> +<div class="get-catalog-list-button">
Est-ce qu'on pourrait mettre une configuration?

2024-02-08 19:29 UTC, pelord commented on packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.ts
> +        .getLocalContexts()
Pour faire l'association des couches du catalogue, afin de connaitre dans quel(s) contexte(s) on les retrouve.

2024-02-08 19:29 UTC, pelord commented on packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.ts
> +      });
non car c'est possible qu'un layer soit présent dans plus d'un contexte.

2024-02-08 19:29 UTC, pelord commented on packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.ts
> +        return `${e.rank}${sep}${e.layerTitle}${sep}${e.layerGroup}${sep}${e.catalog}${sep}${e.provider}${sep}${e.url}${sep}${e.layerName}${sep}${e.context}${sep}${e.dataDescription}`;
Je crain qu'en prenant ceci, on mélange l'ordre des champs dans le csv.

2024-02-15 16:59 UTC, pelord commented on packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.ts
> +    document.body.removeChild(exportDocument);
fait.

2024-02-15 16:59 UTC, pelord commented on packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.html
> +<div class="get-catalog-list-button">
fait.

2024-02-26 14:57 UTC, alecarn commented on packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.ts
> +          });
Avais-tu regarder ce commentaire, est-ce que c'est quelques chose d'optimiser le nombre d'itération et d'éviter la duplication du code pour le csvOutput?

2024-02-26 14:59 UTC, alecarn requested changes

2024-02-26 14:59 UTC, alecarn commented on packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.html
> +<div *ngIf="exportAsListButton" class="get-catalog-list-button">
Ajouter à la documentation?

2024-03-13 13:30 UTC, pelord commented on packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.ts
> +          });
fait.

2024-05-16 16:01 UTC, pelord commented
@alecarn ready for review!

2024-11-29 19:55 UTC, pelord commented
@alecarn pret pour un seconde review.

2024-12-02 18:16 UTC, alecarn commented on packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.ts
> +          const detailedContexts = catalogsAndItemsAndDetailedContexts[1];
```suggestion
       ([catalogsWithItems, detailedContexts]) => {
```

2024-12-02 18:16 UTC, alecarn commented on packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.ts
> +        .getLocalContexts()
J'ai toujours de la difficulté à comprendre ce bout là `getCatalogsAndItemsAndDetailedContexts` et `getCatalogList`, on jumèle deux Observables qui génère deux listes Catalogues et Contextes et ensuite plus bas on reprend ces listes pour gérer de la logique d'affaire par liste. J'ai l'impression qu'on subdivise rapidement les listes ce qui complexifie la lisibilité. 

Catalogue:
1. preloadCatalogItems => Observable
2. Gérer la logique de catalogue items et formatter en**ListExport**

Context:
1. getLocalContexts et preload des contextes => Observable
2. getInfoFromSourceOptions

C'est des petits détails qui ne change pas le fonctionnement mais qui faciliterait la lisibilité/maintenance des prochains développeur.

2024-12-02 18:29 UTC, pelord commented on packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.utils.ts
> +export async function addExcelSheet(
bonne idée! je check ca!

2024-12-02 18:30 UTC, pelord commented on packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.ts
> +    const fn = t.instant('igo.integration.catalog.listExport.documentName', {
filename

2024-12-02 18:38 UTC, pelord commented on packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.ts
> +  public exportAsListButton: boolean;
une relique du passé probablement....

2024-12-02 18:40 UTC, pelord commented on packages/geo/src/lib/catalog/shared/catalog.interface.ts
> +  exportAsListButton?: boolean;
une relique du passé ;(

2024-12-02 18:50 UTC, pelord commented on packages/geo/src/lib/datasource/shared/datasources/any-datasource.utils.ts
> +    context
param est dorénavant required.

2024-12-02 18:59 UTC, pelord commented on packages/geo/src/lib/datasource/shared/datasources/any-datasource.interface.ts
> +export interface InfoFromSourceOptions {
ok. je viens de comprendre ton commentaire. Je sors ca de la.

2024-12-02 19:01 UTC, pelord commented on packages/geo/src/lib/datasource/shared/datasources/any-datasource.utils.ts
je fichier ne sera pas dans le pr, selon ton commentaire précédent.

2024-12-02 19:10 UTC, pelord commented on packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.ts
> +          const detailedContexts = catalogsAndItemsAndDetailedContexts[1];
fait.

2024-12-02 19:15 UTC, pelord commented on packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.ts
> +      layerTitle: t.instant('igo.integration.catalog.listExport.layerTitle'),
fait.

2024-12-02 19:16 UTC, pelord commented on packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.ts
> +    const fn = t.instant('igo.integration.catalog.listExport.documentName', {
remplacé par documentName.

2024-12-04 15:23 UTC, pelord commented
@alecarn Peux tu revalider, j'ai fait les modifs selon tes commentaires.

Je vais travailler aujourd'hui pour faire le PR pour les utilitaires excell et remodifier cette pr après!

2024-12-09 16:36 UTC, pelord commented on packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.utils.ts
> +export async function addExcelSheet(
fait. https://github.com/infra-geo-ouverte/igo2-lib/pull/1709

2025-02-03 20:27 UTC, alecarn approved these changes

2025-04-02 16:44 UTC, pelord commented
superseeded by https://github.com/infra-geo-ouverte/igo2-lib/pull/1748

2025-04-02 16:44 UTC, closed without merging