feat(context): save layer opacity if export context
infra-geo-ouverte/igo2-lib pull request #1322
Opened 2023-07-21 18:28 UTC by aziz-access

**What is the current behavior?** (You can also link to an open issue here)

this behavior related to [#979](https://github.com/infra-geo-ouverte/igo2/issues/979) in igo2

**What is the new behavior?**

Save layer opacity if export contexts
Solve some logical bugs for import and export contexts

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [ ] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**

2023-08-01 13:12 UTC, alecarn requested changes

2023-08-01 13:12 UTC, alecarn commented on package-lock.json
Ce fichier ne devrait pas se retrouver dans la PR, aucune nouvelle installation n'a été fait?

2023-08-01 13:14 UTC, alecarn commented
J'ai eu le temps de tester ça fonctionne pour les WMS mais pour une couche de dessin (VectorLayer) l'opacité ne c'est pas appliqué et la couleur a changé. Voir le screenshot
![image](https://github.com/infra-geo-ouverte/igo2-lib/assets/133774929/51180ff4-b6fa-41c4-a069-e5fec8b7f69c)

2023-08-07 14:20 UTC, alecarn requested changes

2023-08-07 17:31 UTC, alecarn commented on packages/context/src/lib/context-manager/shared/context.service.ts
> +    };
On a ajouté ces propriétés "ol, sourceOptions, source" pour faire plaisir au typage mais est-ce qu'ils sont exporter?
Si oui, il faudrait se faire de nouveau type pour les layers qu'on veut enregistrer dans le contexte, par exemple:  `ContextVectorLayerOptions`. On pourra se parler pour mettre en place une stratégie pour modifier nos types.

2023-08-07 17:38 UTC, aziz-access commented on packages/context/src/lib/context-manager/shared/context.service.ts
> +    };
sans ces propriétés "ol, sourceOptions, source", cela donne une erreur de type, la meilleure façon de créer un nouveau type pour résoudre ce problème.

2023-08-07 21:06 UTC, alecarn approved these changes

2023-09-13 20:21 UTC, pelord reviewed
I'm not sure this is the proper method. Visibility and opacity are layer's property, not a feature or featurecollection. I think it would be more appropriate to find a fix by exporting a layer rather than a feature/featurecollection via attributes (visible/opacity).

2023-09-14 18:09 UTC, merged