feat(context): set map zoom level after importing context
infra-geo-ouverte/igo2-lib pull request #1324
Opened 2023-07-24 19:04 UTC by aziz-access

**What is the current behavior?** (You can also link to an open issue here)

this behavior related to [#981](https://github.com/infra-geo-ouverte/igo2/issues/981) in igo2

**What is the new behavior?**

Set map zoom level after importing context

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [ ] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**

**Other information**:

2023-08-01 17:55 UTC, alecarn requested changes

2023-08-01 17:55 UTC, alecarn commented on packages/context/src/lib/context-manager/shared/layer-context.directive.ts
> +      }
Pourquoi avoir choisi cette directive comme endroit pour controler la vue? 
Est-ce que le ContextService serait un meilleur endroit? Le MapState pourrait faire appel au ContextService pour déterminer la vue?

2023-08-08 20:38 UTC, alecarn requested changes

2023-08-08 20:38 UTC, alecarn commented on packages/context/src/lib/context-manager/shared/map-context.directive.ts
>      }
Ça me semble l'équivalent comme code, je ne vois pas la différence avec le code précédent?
On ajoute cette ligne `this.component.map.setView(viewContext);`  mais au final `this.component.view = viewContext;` fait la même chose.

Il faudrait voir si c'est la méthode `updateView` qui cause problème dans le fichier `MapBrowserComponent`

2023-08-11 17:51 UTC, alecarn requested changes

2023-08-11 17:51 UTC, alecarn commented on packages/geo/src/lib/map/shared/map.ts
>        },
La résolution est une valeur valider pour les options, il ne faudrait pas complètement l'ignorer. Je crois qu'on veut privilégier le zoom si la résolution n'est pas défini dans les options.

* Le `zoom: currentView.getZoom()` ne semble pas servir a rien?
Voici une suggestion:
```suggestion
    const newOptions: MapViewOptions = {
      ...currentView.getProperties(),
      ...options
    };

    if (options.zoom && options.resolution == null) {
      newOptions.resolution = undefined;
    }

    this.setView(newOptions);
```

2023-08-14 14:03 UTC, alecarn requested changes

2023-08-14 14:03 UTC, alecarn commented on packages/geo/src/lib/map/shared/map.ts
> +    if (options.zoom && options.resolution === null) {
`options.resolution == null` le double égale est important parce qu'il considère null ou undefined, tandis que le triple égale va seulement considérer la valeur null.

Surement que tu étais bloqué par la règle Eslint, tu peux aller la modifier dans les fichier `.eslintrc.json` . Tu pourrais changer la valeur `always` pour `smart`.
`"eqeqeq": ["error", "smart"],`

2023-08-14 14:38 UTC, alecarn approved these changes

2023-09-18 14:24 UTC, closed without merging

2023-09-18 14:25 UTC, pelord commented
Superseeded by https://github.com/infra-geo-ouverte/igo2-lib/pull/1384