fix(context): cant load the style for draw layers
infra-geo-ouverte/igo2-lib pull request #1339
Opened 2023-08-09 19:36 UTC by aziz-access

**Please check if the PR fulfills these requirements**

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [ ] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**

**Other information**:

2023-08-15 19:15 UTC, alecarn requested changes

2023-08-15 19:15 UTC, alecarn commented on packages/context/src/lib/context-manager/shared/layer-context.directive.ts
> +            };
Si le type `OlFeature` n'est pas le bon pour la méthode `addImportedFeaturesToMap(olFeatures: OlFeature<OlGeometry>[], ...)`, est-ce qu'on pourrait en créer un qui le représenterait mieux?
```suggestion
type NewType = OlFeature & {name: string; opacity: number; visible: boolean;} 
```

2023-08-15 19:15 UTC, alecarn commented on packages/context/src/lib/context-import-export/shared/context-import.utils.ts
> +    styleListService.getStyleList(layerOptions.title.toString() + '.styleByAttribute')
Lorsqu'on propage une interface avec le type en string, on peut avec confiance enlever le .toString() vu que c'est déjà un string.

2023-08-15 19:15 UTC, alecarn commented on packages/context/src/lib/context-import-export/shared/context-import.utils.ts
> +    source.ol.addFeatures(setCustomFeaturesStyle(olFeatures));
La ligne 234 et 242, font la même chose. On pourrait sortir cette ligne en dehors des conditions, dans tous les scénarios on exécute cette ligne peu importe la condition.

2023-08-15 19:15 UTC, alecarn commented on packages/context/src/lib/context-import-export/shared/context-import.utils.ts
> +    );
Idéalement, il faudrait connaitre le type attendu de ces features. On pourrait ainsi déterminer si c'est sécure de laisser le `drawingStyle.fill` sans optional chaining. Présentement sans interface, je n'ai pas toute l'information nécessaire pour dire si on a des riques de bogues ou non.

2023-08-22 15:18 UTC, alecarn requested changes

2023-08-22 15:18 UTC, alecarn commented on packages/context/src/lib/context-import-export/shared/context-import.utils.ts
> +    const fill = new olStyle.Fill({ color: feature.getProperties().drawingStyle.fill });
On répète `feature.getProperties()` à plusieurs endroits, on pourrait en faire une variable.
Lorsqu'on accède a une propriété de getProperties,  on devrait ajouter [l'opérateur l'optionnal chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) vu qu'il est d'un type générique et que la propriété pourrait être undefined, par exemple: `featureProperties.drawingStyle?.fill`

2023-08-22 15:18 UTC, alecarn commented on packages/geo/src/lib/style/shared/feature/feature-style.ts
> +      });
Pourquoi ajouter ce code dans la méthode `feaureRandomStyle`? 
De ma compréhension et comme son nom l'indique cette méthode génère un style random, alors si on ajoute des valeurs calculés à partir des propriétés du feature ce n'est plus random?

2023-08-22 15:18 UTC, alecarn commented on packages/context/src/lib/context-manager/shared/context.service.ts
> +  private extraFeatures(layer: Layer): ExtraFeatures {
On pourrait ajouter un verbe d'action en préfixe comme parse ou get, ex: `parseExtraFeatures`

2023-08-23 18:22 UTC, alecarn approved these changes
Good job Aziz!

2023-09-13 12:53 UTC, pelord commented
Superseeded by https://github.com/infra-geo-ouverte/igo2-lib/pull/1374

We finally decided to reuse existing feature's properties (_style and _mapTitle) to restore layers from the draw tool on importation (context or layer)

2 questions/enhancement remainning still remain:

- [ ] How to handle internal layer on export/import process ==>  Create/Extend vector layer for internal layer based on geojson features instead of url based data.
- [ ] How to handle internal layer style on export/import process ==> Shorly, we will add a style manager inside the lib, i.e. Geostyler. When geostyler will be strongly implemented and used insite lib and sub project, we will launch a deprecation warning on other custom style management object in lib/project.

2023-09-13 12:56 UTC, closed without merging