fix(context, geo): 1358 keep same circles radius for imported draw layer
infra-geo-ouverte/igo2-lib pull request #1359
Opened 2023-08-28 18:36 UTC by aziz-access

**What is the current behavior?** (You can also link to an open issue here)

This behavior related to #1358 

**What is the new behavior?**

Load circle from draw layer with correct size

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [ ] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**

**Other information**:

2023-08-28 19:22 UTC, alecarn requested changes

2023-08-28 19:22 UTC, alecarn commented on packages/geo/src/lib/style/shared/feature/feature-style.ts
> +  }
Code dupliqué

2023-08-28 19:22 UTC, alecarn commented on packages/context/src/lib/context-import-export/shared/context-import.utils.ts
> +      console.log('has rad: ', feature.get('rad'));
No console.log

2023-09-13 18:35 UTC, closed without merging

2023-09-13 18:35 UTC, pelord commented
Superseeded by https://github.com/infra-geo-ouverte/igo2-lib/pull/1380