fix(geo,common): create new color picker component
infra-geo-ouverte/igo2-lib pull request #1368
Opened 2023-09-06 12:52 UTC by aziz-access

**What is the current behavior?** (You can also link to an open issue here)

This behavior related to #1330 

**What is the new behavior?**

Use native html component `<input type="color">`
Create new color picker component 

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [ ] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**

**Other information**:

2023-09-07 21:17 UTC, alecarn requested changes

2023-09-07 21:17 UTC, alecarn commented on packages/common/src/lib/color-picker/x-color-picker.component.ts
> +  setFormat(color: string): string {
Méthode privée?

2023-09-07 21:17 UTC, alecarn commented on packages/common/src/lib/color-picker/x-color-picker.module.ts
> +  }
Pourquoi ajouter le forRoot?

2023-09-07 21:17 UTC, alecarn commented on packages/geo/src/lib/style/style-modal/drawing/style-modal-drawing.component.html
> +        formControlName="fill"
Pourquoi qu'on a un `ngModel` en plus d'un `formControlName`? J'ai l'impression qu'on essaie d'implémenter deux types de gestion de formulaire en même temps Template Driven vs Reactive Form

2023-09-07 21:17 UTC, alecarn commented on packages/geo/src/lib/style/style-modal/drawing/style-modal-drawing.component.ts
> +    }, 300);
Il faudrait indiquer dans un commentaire pourquoi qu'on ajoute un `setTimeout`. J'ai l'impression que ce setTimeout devrait être géré dans le ColorPickerComponent vu que la raison est du au input color-picker natif?

2023-09-07 21:17 UTC, alecarn commented on packages/geo/src/lib/style/style-modal/layer/style-modal-layer.component.html
> +        ></igo-x-color-picker>
Formatter le code modifié avec Prettier

2023-09-13 13:21 UTC, alecarn requested changes

2023-09-13 13:21 UTC, alecarn commented on packages/common/src/lib/color-picker-form-field/color-picker-form-field.component.ts
> +      this._hexColor = tinycolor(this.color).setAlpha(this.setAlpha).toHexString();
Le hexColor est attaché a un NgModel donc il est dynamique mais dans le getter, on peut overrider la valeur par le `@Input color`? Ça pourrait causer un drole de comportement?

Idéalement si on veut gérer les inputs et les attribuer en tant que valeur par défaut, on utilise les lifecyle d'Angular dans ce cas ci un `ngOnInit` devrait être suffisant.

```suggestion
ngOnInit(): void {
      this.hexColor = this.color;
}
```

2023-09-13 13:33 UTC, alecarn approved these changes

2023-09-13 13:34 UTC, alecarn commented
@pelord ready for your review

2023-09-13 18:53 UTC, pelord approved these changes

2023-09-13 18:56 UTC, merged