fix(geo, common): Integrate ngx color
infra-geo-ouverte/igo2-lib pull request #1422
Opened 2023-09-28 13:06 UTC by aziz-access

**What is the current behavior?** (You can also link to an open issue here)

this behavior integrate ngx-color to solve the issues of color alpha

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [ ] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**

**Other information**:

2023-09-28 20:07 UTC, alecarn commented
@pelord ready for your review

2023-10-02 14:56 UTC, pelord requested changes
Remove console.log pls.

2023-10-02 14:56 UTC, pelord commented on packages/geo/src/lib/style/style-modal/layer/style-modal-layer.component.ts
> +      console.log(res);
Remove this please.

2023-10-02 14:56 UTC, pelord commented on packages/geo/src/lib/style/style-modal/drawing/style-modal-drawing.component.ts
> +      console.log(res);
remove this pls

2023-10-02 15:16 UTC, merged