feat(context): save layer opacity in db
infra-geo-ouverte/igo2-lib pull request #1439
Opened 2023-10-11 16:09 UTC by aziz-access

**What is the current behavior?** (You can also link to an open issue here)

this behavior related to [#979](https://github.com/infra-geo-ouverte/igo2/issues/979) in igo 2

**What is the new behavior?**

save layer opacity in db

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [ ] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**

**Other information**:

2023-10-11 19:52 UTC, alecarn requested changes

2023-10-11 19:52 UTC, alecarn commented on packages/context/src/lib/context-manager/shared/context.service.ts
>          } as LayerOptions,
Les `as` est un peu comme le `any`, on doit l'éviter parce qu'il force un typage sans pour autant respecter l'interface. Au lieu du `as`, on peut utiliser [l'opérateur satisfies](https://typescriptlang.org/docs/handbook/release-notes/typescript-4-9.html#the-satisfies-operator)

2023-10-12 18:55 UTC, alecarn approved these changes
Good job Aziz, je passe la puck à @pelord

2023-10-13 15:27 UTC, pelord requested changes

2023-10-13 16:57 UTC, pelord requested changes

2023-10-13 16:57 UTC, pelord commented on packages/context/src/lib/context-manager/shared/context.service.ts
> +        component: tool.component
pourquoi? je ne comprends pas la raison de passer le tool.component

2023-10-13 17:02 UTC, alecarn commented on packages/context/src/lib/context-manager/shared/context.service.ts
> +        component: tool.component
@aziz-access nous sommes p-t en présence d'un Partial<DetailedContext>?

2023-10-13 17:20 UTC, merged