Geostyler style handler
infra-geo-ouverte/igo2-lib pull request #1487
Opened 2023-11-06 13:51 UTC by ThierryNormand

Added management of a Geostyler layer. It is able to load throught a context, .json file, layers with a geostyler style. 
It reuse already developed method createAsyncLayer. Added part that call geostylerService which use a parser to transform the Geostyle to an OpenLayer style. 

Up to date with Angular 16

2024-01-17 22:01 UTC, pelord requested changes

2024-01-17 22:01 UTC, pelord commented on packages/geo/src/lib/layer/shared/layer.service.ts
> +    let style: Style[] | Style | OlStyleLike = layerOptions.style;
ca ne va pas plutot dans l'autre pr cette section?

2024-01-17 22:01 UTC, pelord commented on packages/geo/src/lib/layer/shared/layers/vector-layer.ts
> +/*
clean up

2024-01-17 22:01 UTC, pelord commented on packages/geo/src/lib/layer/shared/layers/vector-layer.ts
> +    // convertir cet objet this.options.igoStyle.geoStylerStyle en objet ol qui sera appliqué
ca ne va pas plutot dans l'autre pr cette section?

2024-01-17 22:01 UTC, pelord commented on packages/geo/src/lib/map/shared/hover-feature.directive.ts
> +      // style =    geostylerstyle.hover  converti en ol....
ca ne va pas plutot dans l'autre pr cette section?

2024-01-17 22:01 UTC, pelord commented on packages/geo/src/lib/style/shared/vector/vector-style.interface.ts
ca ne va pas plutot dans l'autre pr cette section?

2024-02-22 19:41 UTC, pelord requested changes

2024-02-22 19:41 UTC, pelord commented on packages/geo/src/lib/layer/shared/layer.service.ts
> +  /*, mergeMap*/
cleanup

2024-02-22 19:41 UTC, pelord commented on packages/geo/src/lib/style/geostyler-service/geostyler.service.ts
> +    for (var index in stylesCopy) {
changer vers un foreach si applicable?

2024-02-22 19:41 UTC, pelord commented on packages/geo/src/lib/style/geostyler-service/geostyler.service.ts
> +              (styleRuleSymbolizer as MarkSymbolizer).radius = 10;
faire pour chaque méthode svp

2024-02-23 13:44 UTC, ThierryNormand commented
Les changements demandés ci-haut ont été faits

2024-05-16 15:02 UTC, pelord commented
superseeded by https://github.com/infra-geo-ouverte/igo2-lib/pull/1678

2024-05-16 15:02 UTC, closed without merging