fix(core, integration): fix advanced map tool view and core media det…
infra-geo-ouverte/igo2-lib pull request #1505
Opened 2023-11-17 19:22 UTC by aziz-access

**What is the current behavior?** (You can also link to an open issue here)

this behavior related to #1500 

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [ ] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**

**Other information**:

2023-11-27 15:27 UTC, alecarn approved these changes
@aziz-access pourrais-tu refaire un QA. J'ai apporté quelques modifications a cette PR

2023-11-27 16:03 UTC, aziz-access commented
> @aziz-access pourrais-tu refaire un QA. J'ai apporté quelques modifications a cette PR

@alecarn QA testée et approuvée

2023-11-28 13:26 UTC, pelord requested changes
The demo must be modified to represent theses changes.

![image](https://github.com/infra-geo-ouverte/igo2-lib/assets/7397743/43b1b285-03b0-4a9a-b781-a73df91b42f6)

Check every pages based on map,

2023-11-28 21:39 UTC, pelord approved these changes

2023-11-28 21:41 UTC, merged