refactor(demo): Repaired broken layers, added typing, removed unused imports/variables
infra-geo-ouverte/igo2-lib pull request #1549
Opened 2023-12-18 18:36 UTC by LAMM26

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
Some sections of the "geo" demo had broken tools or layers.

**What is the new behavior?**
Layers have been repaired, typing has been added for claiity, tools (ie. print) have been repaired, imports/varaibles have been cleaned.

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**

**Other information**:

2023-12-18 18:51 UTC, alecarn requested changes

2023-12-18 18:51 UTC, alecarn commented on projects/demo/src/app/geo/catalog/catalog.component.ts
> +      } as LayerOptions)
On essaie autant que possible d'utiliser l'opérateur [`satisfies`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-9.html) au lieu du `as`. Parce que ce dernier force le type et empêche Typescript de faire sa validation du type.

2023-12-18 23:21 UTC, alecarn approved these changes
Look good to me, good job

2023-12-19 16:08 UTC, aziz-access approved these changes

2023-12-27 15:07 UTC, pelord requested changes
Voir les commentaires.

2023-12-27 15:07 UTC, pelord commented on projects/demo/src/app/geo/layer/layer.component.ts
> -            { name: 'rain', title: 'Pluie' },
Cette démo était intéressante pour la définition des styles disponible pour les wms. Une alternative?

2023-12-27 15:07 UTC, pelord commented on projects/demo/src/app/geo/search/search.component.ts
> +      .subscribe((layer: ImageLayer) => this.map.addLayer(layer));
Sould be TileLayer

2023-12-27 15:38 UTC, pelord commented on projects/demo/src/app/geo/layer/layer.component.ts
> -            { name: 'rain', title: 'Pluie' },
@LAMM26 p-etre refaire un pr pour cette demo?

2023-12-27 15:38 UTC, pelord approved these changes
faire un pr pour la demo de stylesavailable svp.

2023-12-27 15:39 UTC, merged

2024-01-15 17:14 UTC, LAMM26 commented on projects/demo/src/app/geo/layer/layer.component.ts
> -            { name: 'rain', title: 'Pluie' },
See https://github.com/infra-geo-ouverte/igo2-lib/pull/1581