feat(context): save attrebute filters associated with layers
infra-geo-ouverte/igo2-lib pull request #1553
Opened 2023-12-19 19:45 UTC by aziz-access

**What is the current behavior?** (You can also link to an open issue here)

this behavier related to [#980](https://github.com/infra-geo-ouverte/igo2/issues/980) in igo2 and the update in igo2-api 

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [ ] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**

**Other information**:

2023-12-20 19:34 UTC, pelord requested changes
Ca ne fonctionne pas aussi simplement. Il faut modifier l'api pour conserver ces parametres.. en tous cas, je crois....

2023-12-20 19:36 UTC, aziz-access commented
> Ca ne fonctionne pas aussi simplement. Il faut modifier l'api pour conserver ces parametres.. en tous cas, je crois....

oui, bien vu, j'ai déjà modifié l'API mais pas encore merger

2023-12-20 20:49 UTC, alecarn commented
@aziz-access n'oublie pas qu'on ne travaille pas dans le tronc commun pour l'instant. On est dans notre version privée du MSP.
@pelord nous allons rapporter les modifs dans le tronc commun une fois qu'on aura terminé

2024-05-13 18:34 UTC, alecarn commented
PR in progress dans notre environnement privé, on ferme pour l'instant

2024-05-13 18:34 UTC, closed without merging