feat(linked-layers): Added new config for visibility in Base Layer Switcher
infra-geo-ouverte/igo2-lib pull request #1560
Opened 2024-01-03 19:35 UTC by LAMM26

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
When a base layer shown in the mini-basemap/preview has linked layers, the linked layers are always shown/visible in the preview. This can lead to performance issues.

**What is the new behavior?**
The new config, showInMiniBaseMap, allows the user to decide if a linked layer should be visible in the preview of a base layer or not.

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**

**Other information**:

2024-01-10 21:15 UTC, aziz-access approved these changes

2024-01-11 14:22 UTC, alecarn requested changes

2024-01-11 14:22 UTC, alecarn commented on packages/geo/src/lib/map/baselayers-switcher/mini-basemap.component.ts
> +      links.map((link: LayersLinkProperties) => {
C'est subjectif mais on n'est pas obligé de tout typer lorsque Typescript est capable de le déduire par inférence. Je trouve que c'est un peu moins lisible mais c'est un beau problème lorsqu'on est rendu là :P

2024-01-11 14:22 UTC, alecarn commented on packages/geo/src/lib/map/baselayers-switcher/mini-basemap.component.ts
> +                : true,
- Pour améliorer la lisibilité, on pourrait utiliser l'opérateur ["Nullish coalescing"](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing) qui permet de renvoyer l'opérande de droit lorsque null ou undefined

```suggestion
                visible: layerToApply.options.linkedLayers?.showInMiniBaseMap ?? true,
```

- Problème d'indentation. 
Est-ce que tu as les extensions de Prettier et Eslint dans VsCode? Si oui, ça devrait formatter automatiquement en sauvegardant.

2024-01-11 14:22 UTC, alecarn commented on packages/geo/src/lib/layer/shared/layers/layer.interface.ts
> +  showInMiniBaseMap?: boolean;
On devrait laisser un commentaire au développeur que la valeur par défaut est vrai et en plus, on ajoute de l'intellisense à notre type.
```suggestion
  /** Default is true */
  showInMiniBaseMap?: boolean;
```

2024-01-17 19:52 UTC, alecarn approved these changes

2024-01-17 21:46 UTC, pelord requested changes

2024-01-17 21:46 UTC, pelord commented on packages/geo/src/lib/layer/shared/layers/layer.interface.ts
> +  showInMiniBaseMap?: boolean; // default value is true
p-etre faire un réel commentaire
/* 
  * Default value to true
  */

dans les IDE, on pourrait le voir directement!

2024-01-18 14:12 UTC, pelord approved these changes

2024-01-18 14:13 UTC, merged