fix(geo): check Capability contains layers list before loop
infra-geo-ouverte/igo2-lib pull request #1570
Opened 2024-01-11 19:44 UTC by aziz-access

**What is the current behavior?** (You can also link to an open issue here)

this behavior related to #1565 

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [ ] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**

**Other information**:

2024-01-29 16:42 UTC, alecarn commented on packages/geo/src/lib/catalog/shared/catalog.service.ts
> +        return EMPTY;
Est-ce qu'on pourrait afficher l'erreur localement au niveau du contexte de l'utilisateur. Par exemple dans la composante CatalogBrowserTool?:
![Capture d’écran 2024-01-29 113848](https://github.com/infra-geo-ouverte/igo2-lib/assets/133774929/850678ae-c24a-4197-ac82-620a19d93c7b)

2024-01-29 17:11 UTC, alecarn requested changes

2024-01-29 17:11 UTC, alecarn commented on packages/geo/src/lib/catalog/shared/catalog.service.ts
> +          catalog.title
Selon la classe du catalogue, le title doit toujours être défini. Est-ce que l'erreur retourner par la requête pourrait nous indiquer quel type de message à afficher? Sinon m'expliquer la logique derrière cette condition.

2024-01-29 19:22 UTC, aziz-access commented on packages/geo/src/lib/catalog/shared/catalog.service.ts
> +          catalog.title
@alecarn cette fonction load les couches du catalogue, parfois le catalogue est vide, n'a pas de couches. j'ajoute le message d'erreur pour informer l'utilisateur que ce catalogue ne fonctionne pas bien.

2024-01-29 20:21 UTC, alecarn commented on packages/geo/src/lib/catalog/shared/catalog.service.ts
> +          catalog.title
Dans quel cas de figure que le title est non défini?

2024-01-30 14:40 UTC, alecarn approved these changes

2024-02-05 21:00 UTC, alecarn commented
@pelord Ready for you review

2024-02-14 13:00 UTC, pelord approved these changes

2024-02-14 14:39 UTC, merged

2024-08-22 16:22 UTC, alecarn commented
:tada: This PR is included in version 17.0.0 :tada:

The release is available on:
- `v17.0.0`
- [GitHub release](https://github.com/infra-geo-ouverte/igo2-lib/releases/tag/v17.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: