feat(magnifying glass): use the magnifying glass to find the first choice to see on the map
infra-geo-ouverte/igo2-lib pull request #1600
Opened 2024-01-24 22:33 UTC by MSPKarengeo

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
N/A

**What is the new behavior?**
The magnifying glass will find the first score that best matches the search to view it on the map

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [X] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**
N/A

**Other information**:

2024-02-05 21:35 UTC, alecarn commented
Pourrais-tu nous indiquer comment qu'on peut tester les changements?

2024-02-05 22:24 UTC, alecarn requested changes

2024-02-05 22:24 UTC, alecarn commented on packages/geo/src/lib/search/search-bar/search-bar.component.ts
> +    // look for the two highest score results
Le commentaire dit qu'on regarde pour les deux plus haut résultats alors qu'on applique seulement un ordonnancement. C'est subjectif mais habituellement je n'ajoute pas de commentaire lorsque le code est lisible et ici je crois que c'est le cas alors j'aurais tendances a ne pas en mettre.

2024-02-05 22:24 UTC, alecarn commented on packages/geo/src/lib/search/search-bar/search-bar.component.ts
> +    // it is necessary to focus and display the layer on the map
Ces deux lignes de commentaires devrait se retrouver au niveau de l'autre condition soit la ligne 514?

2024-02-05 22:24 UTC, alecarn commented on packages/geo/src/lib/search/search-bar/search-bar.component.ts
> +          [feature] satisfies Feature[],
Vu qu'on affirme le type à la ligne 514 `(result as SearchResult<Feature>)`, on n'a pas besoin de le spécifier ici. On pourrait enlever la mention `satisfies Feature[]` parce que Typescript est capable de le déduire par inférence

2024-02-05 22:24 UTC, alecarn commented on packages/geo/src/lib/search/search-bar/search-bar.component.ts
> +          layerOptions.sourceOptions.optionsFromApi = true;
Pourrais-tu m'expliquer qu'est-ce que cela permet de faire?

2024-02-05 22:24 UTC, alecarn commented on packages/geo/src/lib/search/search-results/search-results-add-button.component.ts
>      this.layers$$ = this.map.layers$.subscribe(() => {
Pourquoi avoir déplacer cette ligne, est-ce que ça corrige un bogue?

2024-02-05 22:24 UTC, alecarn commented on packages/geo/src/lib/search/search-bar/search-bar.component.ts
> +
Enlever l'espacement et le commentaire (traduit) est "Lorsque l'utilisateur clique sur la loupe et trouve ainsi le premier objet sur la carte" Est-ce que c'est vraiment ça?

2024-02-06 14:28 UTC, MSPKarengeo commented on packages/geo/src/lib/search/search-results/search-results.component.ts
> +    console.log('return this store ',this.store.stateView.all$() );
désolé ça m'a échappé

2024-02-06 14:30 UTC, MSPKarengeo commented on packages/geo/src/lib/search/search-results/search-results.component.ts
> +    console.log('return this store ',this.store.stateView.all$() );
enlevé

2024-02-06 14:33 UTC, MSPKarengeo commented on projects/demo/src/app/geo/search/search.module.ts
> +    IgoLanguageModule,
Selon ce que je me rappelle on avait besoin pour avoir les deux versions d'igo traduits (français & anglais), je vais faire un test avant de pousser les corrections.

2024-02-16 15:10 UTC, MSPKarengeo commented on packages/geo/src/lib/search/search-bar/search-bar.component.html
> +    <div class="search-bar-buttons">
nouvelle version corrige

2024-02-16 15:10 UTC, MSPKarengeo commented on packages/geo/src/lib/search/search-bar/search-bar.component.ts
> +  @Input() map: IgoMap;
j'ai enlevé le commentaire test

2024-02-16 15:11 UTC, MSPKarengeo commented on packages/geo/src/lib/search/search-bar/search-bar.component.ts
> +
je viens de reformuler la phrase

2024-02-16 15:11 UTC, MSPKarengeo commented on packages/geo/src/lib/search/search-bar/search-bar.component.ts
> +    // look for the two highest score results
merci le commentaire à été enlevé

2024-02-16 15:11 UTC, MSPKarengeo commented on packages/geo/src/lib/search/search-bar/search-bar.component.ts
> +    // it is necessary to focus and display the layer on the map
j'ai modifié les commentaires pour qu'il soit plus claire.

2024-02-16 15:11 UTC, MSPKarengeo commented on packages/geo/src/lib/search/search-bar/search-bar.component.ts
> +          [feature] satisfies Feature[],
j'ai enlevé merci pour la suggestion.

2024-02-19 16:30 UTC, MSPKarengeo commented on projects/demo/src/app/geo/search/search.module.ts
> +    IgoLanguageModule,
j'ai réalisé les test et il marche correctement lorsque j'enlève l'importation de IgoLanguageModule

2024-02-20 19:25 UTC, MSPKarengeo commented on packages/geo/src/locale/en.geo.json
> +        "search":"Search",
j'ai changé le libellé en Français à : Rechercher au lieu de  "Faire une recherche"

2024-02-20 19:26 UTC, MSPKarengeo commented on packages/geo/src/lib/search/search-bar/search-bar.component.ts
> +          layerOptions.sourceOptions.optionsFromApi = true;
après ton commentaire, j'ai fait à nouveau des tests ce qui a permis de reformuler le code alors dans la nouvelle version je pense avec la simple description au début de la condition c'est assez, on simplifie :) !

2024-02-20 21:13 UTC, MSPKarengeo commented
Corrections et modifications on été effectuées. Disponibles pour révision.

2024-03-05 19:48 UTC, alecarn commented on packages/geo/src/lib/search/search-bar/search-bar.component.html
>      <button
Look good!

2024-03-05 20:19 UTC, alecarn requested changes
Deux questionnements sinon ça me semble beau 👍

2024-03-05 20:19 UTC, alecarn commented on packages/geo/src/lib/search/search-bar/search-bar.component.ts
> +    if (results) {
Si on a une liste vide est-ce que ça fonctionne?
Je propose de mettre une validation sur la longueur du tableau. `results.length`

S'il n'y a pas de résultat est-ce que la recherche conserve le dernier élément sélectionné?

2024-03-06 21:14 UTC, MSPKarengeo commented on packages/geo/src/lib/search/search-bar/search-bar.component.ts
> +    if (results) {
Si on a une liste vide est-ce que ça fonctionne? RE: Lorsque on ajoute un caractère ou plusieurs il va sortir toujours la meilleur correspondance soit 3 charactères soit 2 caractères, s'il y a seulement 1 charactère il vais rien chercher (la liste est vide  alors il ne marche pas). 
Je propose de mettre une validation sur la longueur du tableau. results.length : RE: d'après moi on a pas besoin de l'ajouter mais tu peux me donner un exemple pour mieux comprendre le point. 
S'il n'y a pas de résultat est-ce que la recherche conserve le dernier élément sélectionné? RE: Oui , s'il y avait une recherche déjà effectuée.

2024-03-07 12:55 UTC, alecarn commented on packages/geo/src/lib/search/search-bar/search-bar.component.ts
> +    if (results) {
Si tu analyse comme il faut ton code, on prend pour acquis que le Array a toujours au minimum un élément mais il pourrait en avoir aucun

Dans ton code on retrouve cette ligne: ` const result = results[0];` et si le array est vide le resultat sera undefined. 
Ensuite `result.meta.dataType` retournera une erreur parce que tu ne peux pas accéder une propriété d'un objet undefined

2024-03-07 15:32 UTC, MSPKarengeo commented on packages/geo/src/lib/search/search-bar/search-bar.component.ts
> +    if (results) {
je suis totalement d'accord avec ton point, il faut prévoir des retours "undefined". Justement à ça va servir les tests, car n'importe quelle nombre de caractères, il va avoir une correspondance soit un [0], car la recherche est capable de faire le tri dans différents positions  et lorsque il n'a rien, la loupe va rien sortir, dans ce cas là, il faudrait mettre un message? sinon on pourrait faire des tests ensemble et voir comment aborder de la meilleur façon ce point?

2024-03-11 19:59 UTC, alecarn approved these changes

2024-03-13 14:19 UTC, pelord requested changes
J'ai cette erreur.

![image](https://github.com/infra-geo-ouverte/igo2-lib/assets/7397743/9181ee2b-473b-4849-999f-c2c9b4efe330)

2024-11-19 15:44 UTC, aziz-access commented
> J'ai cette erreur.
> 
> ![image](https://private-user-images.githubusercontent.com/7397743/312492460-9181ee2b-473b-4849-999f-c2c9b4efe330.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMjUyNTcsIm5iZiI6MTczMjAyNDk1NywicGF0aCI6Ii83Mzk3NzQzLzMxMjQ5MjQ2MC05MTgxZWUyYi00NzNiLTQ4NDktOTk5Zi1jMmM5YjRlZmUzMzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTlUMTQwMjM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmY0MDE3NjA0NDVkYjk1MjhiMTJkYjM0MDY5NmE2MmZlZmQ5MjBkYmFiZjAxNjk3NGY4YjllY2ZiZjA0ZTZhOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.x2DGPnaMm0UxfsMVuJcvfIcmihRHhe_Tio0-1Hk1pjs)

Il faut ajouter l'input `map` dans le composant `<igo-search-bar>`  portal component (igo2).

![image](https://github.com/user-attachments/assets/0f4a38db-b4fd-4ed2-ae9a-44ab0cfe11c6)

2024-11-19 16:01 UTC, aziz-access commented on packages/geo/src/lib/search/search-results/search-results-add-button.component.ts
>      this.layers$$ = this.map.layers$.subscribe(() => {
cette partie de code a été déplacée pour détecter l'état de la couche et modifier le bouton Ajouter une couche pour supprimer la couche.

![image](https://github.com/user-attachments/assets/29ec331d-191d-4d10-986e-b878f458f94d)

2024-11-21 14:59 UTC, alecarn requested changes

2024-11-26 12:44 UTC, alecarn commented on packages/geo/src/lib/search/search-bar/search-bar.component.html
> +    <div class="search-bar-buttons">
Ce n'était pas corrigé, je pousse un commit.

2024-11-26 12:46 UTC, alecarn commented on packages/geo/src/lib/search/search-bar/search-bar.component.ts
> +          [feature] satisfies Feature[],
Ce n'était pas fait, je pousse un commit pour le régler.

2024-11-26 12:51 UTC, alecarn commented on packages/geo/src/lib/search/search-results/search-results-add-button.component.ts
>      this.layers$$ = this.map.layers$.subscribe(() => {
Mais au final c'est quoi le lien avec cette PR? Est-ce qu'on peut s'en passer et juste focuser sur l'objectif d'implémenter la loupe ou sa corrige un bogue requis pour cette tâche?

2024-11-26 12:59 UTC, aziz-access commented on packages/geo/src/lib/search/search-results/search-results-add-button.component.ts
>      this.layers$$ = this.map.layers$.subscribe(() => {
au cas où le résultat est une couche, il faut ajouter la couche dans la carte. dans ce cas il faut changer l'état du bouton ajouter à supprimer, pour éviter l'ajout de la même couche avec une autre méthode

2024-11-26 15:22 UTC, alecarn approved these changes

2024-11-26 15:24 UTC, alecarn commented
@pelord, ready for review/test

2024-12-04 15:31 UTC, pelord commented
pourquoi pas pousser dans next?

2024-12-04 15:58 UTC, pelord reviewed
Clarifier comment gérer les resultats asynchrone? Les services qui sont plus lent? P-etre tester avec un debouncetime random entre 500 et 2000 ms?

2024-12-04 15:58 UTC, pelord commented on packages/geo/src/lib/search/search-bar/search-bar.component.ts
> +  selectFirstElement() {
Qu'est-ce qui arrive si les résultats ne sont pas tous arrivés lorsque l'utilisateur clique le bouton?

2024-12-04 16:01 UTC, pelord commented on packages/geo/src/lib/search/search-bar/search-bar.component.html
> +      (keydown.enter)="selectFirstElement()"
Est-ce que le keydown.enter ne devrait pas re-trigger la recherche également?

2024-12-04 16:02 UTC, pelord commented on packages/geo/src/lib/search/search-bar/search-bar.component.html
> +      (keydown.enter)="selectFirstElement()"
+ sélectionner le 1er résultat?

2024-12-04 18:21 UTC, aziz-access commented on packages/geo/src/lib/search/search-bar/search-bar.component.ts
> +  selectFirstElement() {
rien ne s'est passé, s'il y a un résultat, le résultat avec le score le plus élevé sera mis en évidence

2024-12-04 18:23 UTC, aziz-access commented on packages/geo/src/lib/search/search-bar/search-bar.component.html
> +      (keydown.enter)="selectFirstElement()"
oui sélectionner  le résultat avec le score le plus élevé

2024-12-04 19:26 UTC, pelord commented on packages/geo/src/lib/search/search-bar/search-bar.component.ts
> +  selectFirstElement() {
Mais disons q'un utilisateur clique sur le boutin ou fait enter, mais que seul des résultats partiels sont disponible?

Quelle est l'échelle relative comparable entre les résultats? Comment comparer des résultats? Regarde computeTermSimilarity

2024-12-04 19:26 UTC, pelord commented on packages/geo/src/lib/search/search-bar/search-bar.component.html
> +      (keydown.enter)="selectFirstElement()"
Je crois que enter devrait redéclancher la recherche.

2024-12-04 19:32 UTC, aziz-access commented on packages/geo/src/lib/search/search-bar/search-bar.component.ts
> +  selectFirstElement() {
chaque résultat a un score donc en utilise le score pour la comparaison

2024-12-04 21:22 UTC, pelord commented on packages/geo/src/lib/search/search-bar/search-bar.component.ts
> +  selectFirstElement() {
Le score est-il comparable entre les services de recherche?

2024-12-04 21:33 UTC, aziz-access commented on packages/geo/src/lib/search/search-bar/search-bar.component.ts
> +  selectFirstElement() {
le code existant bien tester avec iCherche, le résultats de recherche donne le même objet, donc le score existe si le résultat est une couche ou Feature.
existe-t-il un autre service où je peux tester?

2024-12-04 22:32 UTC, pelord commented on packages/geo/src/lib/search/search-bar/search-bar.component.ts
> +  selectFirstElement() {
nominatim?

2025-12-15 13:45 UTC, closed without merging