fix(integration): check if workspace search source is defined
infra-geo-ouverte/igo2-lib pull request #1609
Opened 2024-01-26 20:03 UTC by pelord

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [ ] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**

**Other information**:

2024-02-26 15:07 UTC, alecarn requested changes

2024-02-26 15:07 UTC, alecarn commented on packages/integration/src/lib/search/search.state.ts
> +      if (wksSource) {
Au final, si le wksSource est undefined, est-ce qu'on devrait sauter toute le restant de la méthode?
```suggestion

if (wksSource) {
  return;
}
this.workspaceState.store.entities$.subscribe((e) => {
  const searchableWks = e.filter(
    (fw) =>
      fw instanceof FeatureWorkspace &&
      fw.layer.options.workspace.searchIndexEnabled
  );
  this.searchSourceService.setWorkspaces(wksSource, searchableWks);
});
this.monitorLayerDeletion();
```

2024-03-13 13:59 UTC, pelord commented on packages/integration/src/lib/search/search.state.ts
> +      if (wksSource) {
fait.

2024-03-27 13:26 UTC, alecarn approved these changes

2024-03-28 17:00 UTC, merged

2024-08-22 16:22 UTC, alecarn commented
:tada: This PR is included in version 17.0.0 :tada:

The release is available on:
- `v17.0.0`
- [GitHub release](https://github.com/infra-geo-ouverte/igo2-lib/releases/tag/v17.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: