fix(geo): ensure ogc filter accept today and now
infra-geo-ouverte/igo2-lib pull request #1622
Opened 2024-02-01 20:02 UTC by aziz-access

**What is the current behavior?** (You can also link to an open issue here)

this bug related to [#987](https://github.com/infra-geo-ouverte/igo2/issues/987)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [ ] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**

**Other information**:

2024-02-05 18:22 UTC, alecarn commented
Pourrais-tu nous donner des instructions sur comment qu'on peut tester?

2024-02-05 18:32 UTC, aziz-access commented
> Pourrais-tu nous donner des instructions sur comment qu'on peut tester?

pour le tester en local, vous pouvez utiliser le contexte local dans le projet igo2 'contexts/ogcFilters.json'.
dans le fichier 'ogcFilters.json' tu peux choisir ce layer `"title": "Filtre - Événements (WMS- boutons + filtre temps calendrier-date)"`,  and update dates with the custom format exemple: 
```
"ogcFilters": {
          "enabled": true,
          "editable": true,
          "allowedOperatorsType": "basic",

          "filters": {
            "operator": "During",
            "propertyName": "date_observation",
            "begin": "2016-01-21T00:00:00-05:00",
            "end": "today - 1 days",
            "title": "Date de l'observation"
          }
        },
```
après la modification, vous devez sélectionner le contexte 'Événements de sécurité civile' depuis le menu context.

2024-02-05 18:35 UTC, alecarn requested changes

2024-02-05 18:35 UTC, alecarn commented on packages/geo/src/lib/filter/shared/ogc-filter.ts
> +    const unit: any = [
On ne veut pas de `any`. Pourrais-tu décrire le type d'unité attendu? Par exemple:
```
export const OgcTimeUnit = [
  'years',
  'months',
  'weeks',
  'days',
  'hours',
  'seconds'
] as const;
export type OgcTimeUnit = (typeof OgcTimeUnit)[number];
```

2024-02-05 18:35 UTC, alecarn commented on packages/geo/src/lib/filter/shared/ogc-filter.ts
> +    const sValue = value.toLowerCase().split(' ');
Pour améliorer la lisibilité, on devrait être en mesure de nommer sValue pour exprimer ce qu'elle représente. Rapidement c'est difficile à dire, j'ai l'impression qu'on voudrait plutot appliquer un split à partir de nos opérateurs et ensuite gérer chaque opérande et ses unités?

2024-02-05 19:08 UTC, aziz-access commented on packages/geo/src/lib/filter/shared/ogc-filter.ts
> +    const unit: any = [
type de la variable `unit` lié à la fonction `add()` du moment js, le type doit être `DurationInputArg2`

2024-02-05 19:33 UTC, alecarn commented on packages/geo/src/lib/filter/shared/ogc-filter.ts
> +    const time = date[0];
leftOperand

2024-02-06 14:39 UTC, alecarn commented
S'assurer que lorsqu'on change la valeur du filtrer qu'il est bien appliqué

2024-02-07 16:11 UTC, alecarn requested changes

2024-02-07 16:11 UTC, alecarn commented on packages/geo/src/lib/filter/ogc-filter-time/ogc-filter-time.component.ts
>    changeTemporalProperty(value, position?, refreshFilter = true) {
OUPSY, on avait fixé une partie du problème sur msp-igo2-lib.
Pourrais-tu rapporter le fix (cherry-pick) le commit de msp-igo2-lib qui touche à l'ajout du typage et au fix? 
Si t'as besoin d'aide fait moi signe pour le cherry-pick

Tu pourrais faire un merge des deux solutions, il faut juste s'assurer de ne pas recréer de régression. Tu pourrais aller voir sur JIRA Véronique Payan avait créer un ticket pour ça

2024-02-07 20:31 UTC, aziz-access commented
@alecarn
nous pouvons utiliser ce liste des format date:
opération mathématique addition ou soustraction: 
- `'today + 1 days'` or `'today - 1 days'` or `'now + 1 days'` or `'now - 1 days'` et nous pouvons remplacer "days" par years, months, weeks, hours or seconds.
- `'today'` or `'now'`.
- `'2016-01-21T00:00:00-05:00'`.

![Clipboard - 7 février 2024 17_12](https://github.com/infra-geo-ouverte/igo2-lib/assets/119948730/d8fb3bde-4550-497e-819a-f08214444951)

2024-02-13 12:26 UTC, alecarn approved these changes

2024-02-13 12:27 UTC, alecarn commented
@pelord Ready for your review

2024-05-15 19:05 UTC, merged

2024-08-22 16:22 UTC, alecarn commented
:tada: This PR is included in version 17.0.0 :tada:

The release is available on:
- `v17.0.0`
- [GitHub release](https://github.com/infra-geo-ouverte/igo2-lib/releases/tag/v17.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: