feat(geo): split the add catalog dialog in tabs, predefined catalog a…
infra-geo-ouverte/igo2-lib pull request #1630
Opened 2024-02-08 15:29 UTC by pelord

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
If we configure composite catalogs to be added to the predefined list, the catalogs is not added to the catalog store.

**What is the new behavior?**
Refactor the add catalog dialog to split predefined catalog and custom catalogs. 

![chrome_2024-02-08_10-10-34](https://github.com/infra-geo-ouverte/igo2-lib/assets/7397743/900c7390-efd6-4529-a8cd-8ba7fc512dcb)

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [ ] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**

**Other information**:

2024-02-26 16:11 UTC, alecarn requested changes
Première ronde terminée, je n'ai pas testé encore

2024-02-26 16:11 UTC, alecarn commented on packages/geo/src/lib/catalog/catalog-library/catalog-library.component.ts
> +            ) as Catalog
Deux points ici,
1. On retrouve un double removeUndefined et est-ce qu'on a réellement besoin d'enlever les undefined, pourquoi?
2. Avec l'assertion du type `as Catalog`, on perd tout le bénéfice du typage Typescript. Est-ce qu'on peut le mettre au niveau de la constante?

2024-03-13 13:35 UTC, pelord commented on packages/geo/src/lib/catalog/catalog-library/catalog-library.component.ts
> -        }
non car le titre est une propriét obligatoire

2024-03-13 13:35 UTC, pelord commented on packages/geo/src/lib/catalog/catalog-library/catalog-library.component.ts
> +    this.addedCatalogs = newCatalogs;
fait.

2024-03-13 13:36 UTC, pelord commented on packages/geo/src/lib/catalog/catalog-library/catalog-library.component.ts
> +            ) as Catalog
ok

2024-03-13 13:37 UTC, pelord commented on packages/geo/src/lib/catalog/catalog-library/catalog-library.component.ts
> +          : predefinedCatalog.removable;
fait.

2024-03-13 13:38 UTC, pelord commented on packages/geo/src/lib/catalog/catalog-library/catalog-library.component.ts
> +        c.id ??
vu que ca arrive d'un json, c'est pas impossible que ce soit vide.

2024-03-13 13:39 UTC, pelord commented on packages/geo/src/lib/catalog/catalog-library/catalog-library.component.ts
> +        (Md5.hashStr((c.type || 'wms') + standardizeUrl(c.url)) as string);
fait.

2024-03-13 13:39 UTC, pelord commented on packages/geo/src/locale/fr.geo.json
> +        "library.custom": "Saisir vos propres informations",
Configuration avancées

2025-02-03 20:48 UTC, alecarn approved these changes

2025-04-02 14:31 UTC, pelord commented
Remplacé par [add-catalog-splitted-tabs_v18.0.0](https://github.com/infra-geo-ouverte/igo2-lib/pull/1745)

2025-04-02 14:31 UTC, closed without merging