Fix importing vector
infra-geo-ouverte/igo2-lib pull request #1637
Opened 2024-02-16 19:26 UTC by pelord

fix https://github.com/infra-geo-ouverte/igo2/issues/1146

2024-02-26 18:16 UTC, alecarn requested changes
Un commentaire de style sinon c'est bien beau, good job

2024-02-26 18:16 UTC, alecarn commented on packages/geo/src/lib/map/shared/projection.utils.ts
> +  reader.onload = (e) => {
Présentement, on utilise un BehaviorSubject pour communiquer un output mais une alternative intéressante serait d'utiliser une Promesse ou un Observable pour wrapper le reader et controller la sortie.

```suggestion
export function detectFileEPSG(file: File, nbLines: number = 500): Promise<string> {
  // ... implementation
  const reader = new FileReader();
  reader.readAsText(file, 'UTF-8');

  return new Promise((resolve) => {
    reader.onload = (e) => {
      // ... implementation
      const espg = "...";
      resolve(epsg);
    }
  })
```

```
const epsg = await detectFileEPSG(file);
```

2024-03-13 11:22 UTC, pelord commented on packages/geo/src/lib/map/shared/projection.utils.ts
> +  reader.onload = (e) => {
fait.

2024-03-28 17:15 UTC, alecarn approved these changes
Un seul commentaire à valider avant de merger

2024-03-28 17:15 UTC, alecarn commented on packages/geo/src/lib/import-export/shared/drop-geo-file.directive.ts
>        this.epsgCode$$.push(
J'ai l'impression que ce n'est pas utilisé?

2024-04-02 13:47 UTC, merged

2024-08-22 16:22 UTC, alecarn commented
:tada: This PR is included in version 17.0.0 :tada:

The release is available on:
- `v17.0.0`
- [GitHub release](https://github.com/infra-geo-ouverte/igo2-lib/releases/tag/v17.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: