feat(integration, common, geo): keep selected catalog when changing tools
infra-geo-ouverte/igo2-lib pull request #1654
Opened 2024-03-12 14:27 UTC by aziz-access

**What is the current behavior?** (You can also link to an open issue here)

this behavior related to [#1007](https://github.com/infra-geo-ouverte/igo2/issues/1007) in igo2

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [ ] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**

**Other information**:

2024-03-12 17:28 UTC, pelord commented on packages/geo/src/lib/catalog/catalog-library/catalog-library.component.ts
> +    this.storageService.set('selectedCatalogId', catalogId);
Ça devrait être dans le scope de session a mon avis

2024-03-13 18:41 UTC, alecarn requested changes

2024-03-13 18:41 UTC, alecarn commented on package-lock.json
Pourquoi qu'on retrouve le package-lock?

2024-03-13 18:41 UTC, alecarn commented on packages/common/src/lib/tool/shared/toolbox.ts
> +    );
Qu'arrive t'il si on a un seul élément dans le tableau? Le current est attribué au previous, est-ce quelque chose de possible?

Shortcut:
```suggestion
    const [previous, current] = this.toolHistory.slice(-2);
```

2024-03-14 13:36 UTC, aziz-access commented on package-lock.json
après npm install le  package-lock change. je vais essayer de le résoudre.

2024-03-14 13:47 UTC, aziz-access commented on packages/common/src/lib/tool/shared/toolbox.ts
> +    );
oui  le current est attribué au previous si il y a un seul élément dans le tableau.

2024-03-14 15:43 UTC, alecarn commented on packages/common/src/lib/tool/shared/toolbox.ts
> +        .concat([tool.name]);
Est-ce qu'ils sont équivalent?

2024-03-14 15:45 UTC, aziz-access commented on packages/common/src/lib/tool/shared/toolbox.ts
> +        .concat([tool.name]);
non, chacun a son propre fonction

2024-03-14 15:45 UTC, alecarn commented on packages/common/src/lib/tool/shared/toolbox.ts
> +    );
Dans ce cas ce n'est pas le previous mais le current! On devrait géré ce cas de figure.

2024-03-14 15:47 UTC, aziz-access commented on packages/common/src/lib/tool/shared/toolbox.ts
> +    );
ok

2024-03-14 19:43 UTC, alecarn requested changes

2024-03-14 19:43 UTC, alecarn commented on packages/common/src/lib/tool/shared/toolbox.ts
> +        .concat([tool.name]);
Pour éviter la confusion entre ces deux historiques, je propose de conserver la logique du `activeToolHistory` et de créer une propriété pour stocker le `previousToolName`?
Comme ça tu aurais accès au previous et au current tool name. Le current serait déduit à partir du `activeToolHistory`.

2024-03-27 12:37 UTC, alecarn approved these changes

2024-03-27 12:38 UTC, alecarn commented
@pelord ready for you review

2024-05-15 19:09 UTC, merged

2024-08-22 16:22 UTC, alecarn commented
:tada: This PR is included in version 17.0.0 :tada:

The release is available on:
- `v17.0.0`
- [GitHub release](https://github.com/infra-geo-ouverte/igo2-lib/releases/tag/v17.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: