Package downloader tool
infra-geo-ouverte/igo2-lib pull request #1656
Opened 2024-03-13 20:28 UTC by olivierSaintCyr

**What is the current behavior?** (You can also link to an open issue here)
This feature is related to #1655

**What is the new behavior?**
package-manager: download and remove packages from device.
package-manager-tool: tool for interfacing with the package manager
geo-db: Now data can be in two region ids.
tile-layer: load the tile from geodb when offline.

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

2024-03-13 20:28 UTC, olivierSaintCyr commented on packages/geo/src/lib/offline/geoDB/geoDB.service.ts
> +            console.log('region already there');
```suggestion
```

2024-08-01 15:11 UTC, pelord requested changes

2024-08-01 15:11 UTC, pelord commented on packages/geo/src/lib/offline/geoDB/geoDB.service.ts
> +          return this.customUpdate(dbObject);
Change required. Updating the source object, not the new one ;)

2026-01-12 13:51 UTC, alecarn commented
Je ferme pour l'instant, on y reviendra au besoin plus tard

2026-01-12 13:51 UTC, closed without merging