fix(context): add workspace option with layers when we export context
infra-geo-ouverte/igo2-lib pull request #1660
Opened 2024-03-19 15:50 UTC by aziz-access

**What is the current behavior?** (You can also link to an open issue here)

this behavior related to [#1143](https://github.com/infra-geo-ouverte/igo2/issues/1143) in igo2

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**

**Other information**:

2024-03-27 13:52 UTC, alecarn commented on packages/context/src/lib/context-manager/shared/context.service.ts
>          };
@pelord @aziz-access, On jase... pensez-vous qu'il y a une raison pour ne pas exporter tous les options du layer? Par exemple:
```suggestion
     const opts: AnyLayerOptions = {
          ...layerFound,
          title: layer.options.title,
          zIndex: layer.zIndex,
          style: layerStyle,
          visible: layer.visible,
          opacity: layer.opacity,
        };
```

2024-03-27 14:05 UTC, pelord commented on packages/context/src/lib/context-manager/shared/context.service.ts
>          };
P-etre un lien avec l,API? aucune idée franchement, je ne me sers pas ce ce feature.

2024-04-04 19:03 UTC, alecarn requested changes

2024-04-04 19:03 UTC, alecarn commented on packages/context/src/lib/context-manager/shared/context.service.ts
>          };
@aziz-access Pense-tu que ce serait une bonne idée d'utiliser les modifs proposé dans mon commentaire. On délèguerait la responsabilité a l'API de bien gérer la donnée et nous on protègerais de future changements qu'on pourrait oublier.

2024-04-04 20:38 UTC, aziz-access commented on packages/context/src/lib/context-manager/shared/context.service.ts
>          };
Oui bonne idée, on laisse la responsabilité à l'AP.

2024-04-09 19:05 UTC, alecarn approved these changes

2024-05-15 19:10 UTC, merged

2024-08-22 16:21 UTC, alecarn commented
:tada: This PR is included in version 17.0.0 :tada:

The release is available on:
- `v17.0.0`
- [GitHub release](https://github.com/infra-geo-ouverte/igo2-lib/releases/tag/v17.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: