fix(integration): update latitude and longitude if coords system change
infra-geo-ouverte/igo2-lib pull request #1661
Opened 2024-03-19 20:02 UTC by aziz-access

**What is the current behavior?** (You can also link to an open issue here)

this behavior related to [#1149](https://github.com/infra-geo-ouverte/igo2/issues/1149) in igo2

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**

**Other information**:

2024-03-21 13:18 UTC, pelord requested changes

2024-03-21 13:18 UTC, pelord commented on packages/integration/src/lib/map/advanced-map-tool/advanced-coordinates/advanced-coordinates.component.ts
>        .pipe(debounceTime(50))
pourquoi ne pas combiner les 2 events? via un combineLatest? ca eviterais de trainer 2 subcriptions.

2024-03-21 13:18 UTC, pelord commented on packages/integration/src/lib/map/advanced-map-tool/advanced-coordinates/advanced-coordinates.component.ts
> +
voir commentaire ci haut.

2024-03-21 13:26 UTC, aziz-access commented on packages/integration/src/lib/map/advanced-map-tool/advanced-coordinates/advanced-coordinates.component.ts
>        .pipe(debounceTime(50))
j'ai traiter chaque événement à part pour résolu l'issue de boucle infini pour la mise a ajour de l'input de la form.
vous pouvez vérifier ce issue pour plus de détails.
https://github.com/infra-geo-ouverte/igo2-lib/issues/1606

2024-03-28 18:23 UTC, alecarn requested changes

2024-03-28 18:23 UTC, alecarn commented on packages/integration/src/lib/map/advanced-map-tool/advanced-coordinates/advanced-coordinates.component.ts
> +    this.setScaleValue(this.map);
Il n'y a pas de lien entre l'update de la coordonnée et le scale. Je déplacerais cette méthode dans le subscribe du `this.map.viewController.state$`

2024-03-28 18:23 UTC, alecarn commented on packages/integration/src/lib/map/advanced-map-tool/advanced-coordinates/advanced-coordinates.component.ts
> +    this.cdRef.detectChanges();
Est-ce qu'on a de besoin de ce changement de détection?

2024-03-28 20:14 UTC, aziz-access commented on packages/integration/src/lib/map/advanced-map-tool/advanced-coordinates/advanced-coordinates.component.ts
> +    this.cdRef.detectChanges();
oui, nous avons besoin de changement de détection pour assurer la mise à jour du formulaire

2024-04-04 18:21 UTC, alecarn approved these changes

2024-04-04 18:21 UTC, alecarn commented
@pelord ready for your review

2024-05-15 19:11 UTC, merged

2024-08-22 16:22 UTC, alecarn commented
:tada: This PR is included in version 17.0.0 :tada:

The release is available on:
- `v17.0.0`
- [GitHub release](https://github.com/infra-geo-ouverte/igo2-lib/releases/tag/v17.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: