fix(geo): Print set the same horizontal margin for the map
infra-geo-ouverte/igo2-lib pull request #1662
Opened 2024-03-21 16:57 UTC by aziz-access

**What is the current behavior?** (You can also link to an open issue here)

this behavior related to #1594 

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**

**Other information**:

2024-03-28 15:44 UTC, alecarn requested changes
Quelques petits commentaire mais ça me semble correct. Je n'ai pas testé par contre.

2024-03-28 15:44 UTC, alecarn commented on packages/geo/src/lib/print/shared/print.service.ts
> +      }
```suggestion
      if (!imageDimensions) {
        imageDimensions = this.getImageSizeToFitPdf(doc, canvas, margins);
      }
```

2024-03-28 15:44 UTC, alecarn commented on packages/geo/src/lib/print/shared/print.service.ts
> +    imageDimensions?: Array<number>
On devrait être plus précis dans la définition du type ` imageDimensions?: [number, number]`

2024-03-28 15:44 UTC, alecarn commented on packages/geo/src/lib/print/shared/print.service.ts
> +        imageSize = this.getImageSizeToFitPdf(doc, canvas, margins);
Cette méthode auparavant était toujours appelé et permettait d'ajuster les dimensions d'une image tout en respectant le ratio. Je n'ai pas testé mais il faut s'assurer que cette règle de ratio soit respecté sur la carte peut s'en passer vu qu'on fait un refresh de celle ci.

2024-04-02 17:03 UTC, aziz-access commented on packages/geo/src/lib/print/shared/print.service.ts
> +      margins[2] += 10;
> Il faudrait éviter les "Magic Number", qu'est-ce que représente cet espacement de 10 ou quel est la logique derrière. Idéalement, il faudrait la stocker dans une constante et la nommer adéquatement pour qu'on comprenne ce qu'elle représente ou sinon laisser un commentaire explicatif. Même chose ci-dessous avec le += 5 pourquoi 5?

Magic Number (+=5, +=10) sont l'espacement entre la carte et le text (commentaire et projection). je vais appliquer une autre façon...

2024-04-04 18:59 UTC, alecarn requested changes
Améliorer la lisibilité et les termes choisi pour certains paramètres

2024-04-04 18:59 UTC, alecarn commented on packages/geo/src/lib/print/shared/print.service.ts
> +    const commentProjScaleMargen: number = 10;
Typo? Margen vs Margin
Lorsqu'on ajoute un commentaire pour expliquer une variable est un signe qu'on la probablement mal nommé.

Proposition: baseMargin

2024-04-04 18:59 UTC, alecarn commented on packages/geo/src/lib/print/shared/print.service.ts
> +    const commentMarginBottom = margins[2];
marginBottom pourrait suffire car le nom de la méthode nous indique le context du `comment`

2024-04-04 18:59 UTC, alecarn commented on packages/geo/src/lib/print/shared/print.service.ts
> +      commentProjScaleMargin;
Les calculs sont difficiles à suivre, je crois que les termes utilisé pourriat être améliorée. Par exemple, différencié une postion d'une marge.

Aussi, est-ce qu'on pourrait conserver cette méthode clean et utilisé le paramètre margin pour la configurer par exemple ici on passe le paramètre `commentProjScaleMargin` pour ajuster le margin bottom alors que ça pourrait être fait en amont et enlever ce fameux paramètre mystérieux.

On pourrait se reparler de vive voix si ce n'est pas clair
margins = [10, 10, 20, 10]
yPosition = doc.internal.pageSize.height -

2024-04-09 13:15 UTC, alecarn requested changes

2024-04-12 13:27 UTC, aziz-access commented on packages/geo/src/lib/print/shared/print.service.ts
> +   * @param margin - change map height and calculate text position
> On pourrait améliorer le commentaire, est-ce qu'on change la hauteur de la carte?

oui ici avec `margin` on change la hauteur de la carte

2024-04-24 19:17 UTC, alecarn approved these changes

2024-05-15 19:11 UTC, merged

2024-08-22 16:21 UTC, alecarn commented
:tada: This PR is included in version 17.0.0 :tada:

The release is available on:
- `v17.0.0`
- [GitHub release](https://github.com/infra-geo-ouverte/igo2-lib/releases/tag/v17.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: