Draft: Refactor Edition Workspace
infra-geo-ouverte/igo2-lib pull request #1671
Opened 2024-04-17 19:11 UTC by olivierSaintCyr

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**
A refactor of the edition workspace logic #1667

**Does this PR introduce a breaking change?** (check one with "x")
- [x] Yes
- [ ] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**
Remove of the send attribute in EditionOptions due to redundancy with readonly attribute

**Other information**:

2024-04-22 13:26 UTC, alecarn requested changes
Un premier tour de revue pour me familiariser avec le code, c'est bien partie👍 
Commentaire générale, améliorer le typage pour solidifier nos bases

2024-04-23 15:09 UTC, olivierSaintCyr commented on packages/geo/src/lib/workspace/shared/new-edition-workspace/edition-table-template-factory.ts
> +        const ol = (entities[0] as Feature).ol as olFeature<OlGeometry>;
Bonne idée! Je le change tout de suite!

2024-04-23 15:19 UTC, olivierSaintCyr commented on packages/geo/src/lib/workspace/shared/new-edition-workspace/edition-table-template-factory.ts
> +    });
Oui j'aurais aimer ça que nous aurons pus projeter les changement plus profond. Avant on utilisais un object boolean loading qui était insérer dans le template pour activé et desactiver les boutons. Par contre, ceci entrainais un bug. Le bug était que les boutons ne se disable pas lorsque que loading est set a true vu que l'interpreteur js avait copier la valeur de l'attribut loading et non la référence vu qu'un boolean est un object primitif. Alors il fallait trouver un moyen d'aller update le template directement afin que les changement se propage dans le UI. C'est pourquoi j'ai décider de subscribe sur l'observable isLoading$ afin de découpler le workspace du table template et laisser la responsabilité au template factory de setup le template!

2024-04-23 16:08 UTC, olivierSaintCyr commented on packages/geo/src/lib/workspace/shared/new-edition-workspace/edition-workspace-factory.service.ts
> +  providedIn: 'root'
Nous avons pas besoin de l'exposer globallement nice catch j'ai limiter le export uniquement au new-edition-workspace

2024-04-23 17:59 UTC, olivierSaintCyr commented on packages/geo/src/lib/workspace/shared/new-edition-workspace/edition-table-template-factory.ts
> +  ) {
Jai typer les columns par contre certains attributs ne sont pas dans l'interface EntityTableColumn et en les retirant le UI silent fail. Malheuresement je pense pas avoir le temps dans mon mandat pour le fix. Je vais rajouter un TODO pour pas qu'on oublie de le faire!

2024-04-23 18:01 UTC, olivierSaintCyr commented on packages/geo/src/lib/workspace/shared/new-edition-workspace/edition-table-template-factory.ts
> +    const columns: unknown[] = sourceFieldsColumns;
Voir le commentaire plus haut!

2024-04-23 18:20 UTC, olivierSaintCyr commented on packages/geo/src/lib/workspace/shared/new-edition-workspace/edition-table-template-factory.ts
> +  ) {
voir commentaire plus haut!

2024-04-23 18:21 UTC, olivierSaintCyr commented on packages/geo/src/lib/workspace/shared/new-edition-workspace/new-edition-workspace.ts
> +    this.http[modifyMethod ?? 'patch'](url, this.getUpdateBody(feature), {
Done! Jai modifier les valeur de modifyMethod pour 'patch' | 'post'

2024-04-23 18:32 UTC, olivierSaintCyr commented on packages/geo/src/lib/workspace/shared/new-edition-workspace/new-edition-workspace.ts
> +    });
Personnellement je pense que oui car la classe qui utilise ces methods est le EditionWorkspaceFactory et lui a uniquement une tache créer les edition-workspace . Nous pourrions créé un service qui wrap les workspaces et call les methods add modify etc. ce qui va potentiellement augmenter la complexité. Bref, TBD

2024-04-23 19:12 UTC, olivierSaintCyr commented on packages/geo/src/lib/workspace/shared/layer-workspace.ts
> +export type LayerWorkspace =
Done!

2024-04-23 19:44 UTC, merged