feat(geo): print add option to show hide north arrow direction
infra-geo-ouverte/igo2-lib pull request #1672
Opened 2024-04-19 17:41 UTC by aziz-access

**What is the current behavior?** (You can also link to an open issue here)

this behavior related to #1596 

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [ ] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**

**Other information**:

2024-04-22 17:26 UTC, alecarn requested changes
Un  petit changement sinon

2024-04-22 17:26 UTC, alecarn commented on packages/geo/src/lib/print/shared/print.service.ts
> +  addNorthDirectionArrow(
C'est utilisé a quel endroit cette méthode?

2024-04-22 17:26 UTC, alecarn commented on packages/geo/src/lib/print/shared/print.service.ts
> +        console.log(e);
COnsole log?

2024-04-22 17:26 UTC, alecarn commented on packages/geo/src/lib/print/shared/print.service.ts
> +          await this.createNorthDirectionArrow(map);
Pourquoi qu'on retrounve à deux endroits createNorthDirectionArrow?
Avant il était centralisé dans une méthode, peut-être conserver la même stratégie!

2024-04-22 18:48 UTC, aziz-access commented on packages/geo/src/lib/print/shared/print.service.ts
> +          await this.createNorthDirectionArrow(map);
> Pourquoi qu'on retrounve à deux endroits createNorthDirectionArrow? Avant il était centralisé dans une méthode, peut-être conserver la même stratégie!

on a deux types d'export 'PDF' et 'IMAGE', c'est pourquoi vous le trouvez deux fois.
je vais essayer d'utiliser la même stratégie qu'avant...

2024-04-24 12:31 UTC, alecarn approved these changes

2024-05-24 14:29 UTC, merged

2024-08-22 16:21 UTC, alecarn commented
:tada: This PR is included in version 17.0.0 :tada:

The release is available on:
- `v17.0.0`
- [GitHub release](https://github.com/infra-geo-ouverte/igo2-lib/releases/tag/v17.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: