refactor/ui(directions): directions component refactor
infra-geo-ouverte/igo2-lib pull request #1685
Opened 2024-05-31 18:52 UTC by LAMM26

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
After having deployed the private routing option and having multiple feedback from different users on the component, many features were not clear or unknown to many of them and/or the UI was not user-friendly.

**What is the new behavior?**
- Code refactored for the main component and its sub-components, including cleaning the code, adding strong-typed code, deleting unused classes, methods, variables, etc.
- Changes to UI:
    - Placeholder in stop to indicate what action the user can do.
    - Formatting of coordinates of stop.
    - 'Add intermediate stop' button moved between starting point end destination stops.
    - Actions (zoom, copy, download) moved below inputs for added clarity.
    - Move stop, clear stop and delete stop always showing, not only on hover.
    - Icons changed in steps
    - Better formatting of duration and distance travelled.
    - Formatting and adjustments of copied directions and download directions
- New feature:
    - When tracking is active, the user can select his current location as a stop

![image](https://github.com/infra-geo-ouverte/igo2-lib/assets/83651899/951dff7c-6966-42e8-a6e8-b55c42de3801)

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**

**Other information**:

2024-08-22 15:25 UTC, alecarn requested changes
Premier tests
1.  À l'ajout d'un premier point , on déclanche la requête et on obtient une erreur. Tout comme au deuxième ![image](https://github.com/user-attachments/assets/854f22d4-0e15-4f33-ad12-4b68c529b39b)
2. Modifier la coordonée directement dans l'input ne change pas la position sur la carte et ne trigger pas une nouvelle recherche d'itinéraire.

Proposition:
1. Est-ce qu'on pourrait afficher les boutons de drag et de supression seulement lorsqu'on hover la ligne avec le curseur?
3. Avoir au moins un point de départ et d'arrivée avant de proposer d'ajouter un point intermédiaire?
4. Google Map, au lieu d'ajouter un point intermédiaire, ils utilisent ajouter une destination et il positionne le bouton à la fin.

2024-08-22 15:25 UTC, alecarn commented on packages/geo/src/lib/directions/shared/directions.service.ts
> +  }*/
Faire le ménage, supprimer le code commenté

2024-08-22 15:25 UTC, alecarn commented on packages/geo/src/lib/print/shared/print.service.ts
> +import { Size } from 'ol/size';
On ajoute une nouvelle dépendance à Openlayers. Idéalement, on aimerait faire abstraction de Ol pour les types lorsqu'on peut le faire.

2024-08-22 15:25 UTC, alecarn commented on packages/geo/src/lib/directions/directions.component.ts
>    @Input() authenticated$: BehaviorSubject<boolean>;
On pourrait améliorer la composition en spécifiant quel @Input est requis, par ex: `@Input({ required: true })`

2024-09-17 20:16 UTC, LAMM26 commented on packages/geo/src/lib/directions/shared/directions.interface.ts
> +export interface Directions {
Purement sémantique, en anglais 'Direction' est une direction cardinale (nord, est, droite, gauche), 'Directions' est la série d'instructions pour aller à un endroit, ce qui fait plus de sens dans le contexte. Google Maps parle de 'Directions' par exemple

2024-09-17 20:19 UTC, LAMM26 commented on packages/geo/src/lib/print/shared/print.service.ts
> +import { Size } from 'ol/size';
Je vais changer pour `number[]`

2024-09-20 18:58 UTC, LAMM26 commented
> Premier tests
> 
> 1. À l'ajout d'un premier point , on déclanche la requête et on obtient une erreur. Tout comme au deuxième ![image](https://private-user-images.githubusercontent.com/133774929/360528721-854f22d4-0e15-4f33-ad12-4b68c529b39b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NTg1MzYsIm5iZiI6MTcyNjg1ODIzNiwicGF0aCI6Ii8xMzM3NzQ5MjkvMzYwNTI4NzIxLTg1NGYyMmQ0LTBlMTUtNGYzMy1hZDEyLTRiNjhjNTI5YjM5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQxODUwMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YzExYTM1ZTEwZGViZDIwNGJhODZkZjVlMTI5YjM0ZmJiY2Q3MDE1Mjc1OTE0YTgxMWQ3ZmU1YjZmZmY3MTAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Znu0Ss-Ky2tuiY9wAsDKYm-D8qyODpb7_bXs7Qp1p7w)
> 2. Modifier la coordonée directement dans l'input ne change pas la position sur la carte et ne trigger pas une nouvelle recherche d'itinéraire.
> 
> Proposition:
> 
> 1. Est-ce qu'on pourrait afficher les boutons de drag et de supression seulement lorsqu'on hover la ligne avec le curseur?
> 2. Avoir au moins un point de départ et d'arrivée avant de proposer d'ajouter un point intermédiaire?
> 3. Google Map, au lieu d'ajouter un point intermédiaire, ils utilisent ajouter une destination et il positionne le bouton à la fin.

Je ne suis pas capable d'avoir l'erreur au premier et deuxième clic.

Changer le texte des coordonnées ne change pas la pin en effet mais il iCherche devrait faire une nouvelle proposition. J'ai enlever le comportement qu'on doit cliquer sur le x rouge avant de pouvoir sélectionner un nouveau point dans la carte aussi.

J'ai mis le drag et le delete au hover seulement. On ajoute aussi une destination maintenant.

2024-10-30 17:54 UTC, alecarn commented
À l'ouverture du panneau de direction, j'obtiens ces erreurs:
![image](https://github.com/user-attachments/assets/05fc5126-23bd-451a-a1c1-0e44e92ceaae)

2024-11-04 15:35 UTC, alecarn commented
Ça me semble bien fonctionner!

Commentaire UI:
- Est-ce possible d'éliminer le layout shifting, lorsqu'on hover un input on affiche le bouton de drag mais l'input se tasse vers la droite. On pourrait p-t mettre le bouton a `visibility hidden` au lieu `display none`?
![image](https://github.com/user-attachments/assets/5ed2eec7-7af3-481a-922b-ae6d9b22901a)
- Je proposerais aussi de diminuer au maximum la taille du bouton de drag soit à une densité de -5 (`npm run postbuild -w @igo2/core` pour compiler les thèmes. Ensuite un refresh du navigateur)
![image](https://github.com/user-attachments/assets/aa010251-c431-4ebf-9979-816a386ca3ca)

2024-11-05 13:47 UTC, alecarn approved these changes

2024-11-05 13:48 UTC, alecarn commented
@pelord si jamais tu veux jeter un oeil, des améliorations aux UI de direction

2025-02-03 18:28 UTC, merged