Add the possibility to configure the offline capabilities
infra-geo-ouverte/igo2-lib pull request #1700
Opened 2024-10-31 18:31 UTC by alecarn

(cherry picked from commit 7f63a56aa3256c660d77c0d5cbd8649e54415195)

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [ ] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**

**Other information**:

2024-11-08 21:10 UTC, pelord requested changes
J'ai encore des erreurs, je ne vois pas comment la reproduire.....

2024-11-08 21:10 UTC, pelord commented on packages/geo/src/lib/offline/offline.interface.ts
j'aurais tendance a placer cela and AppOptions
https://github.com/infra-geo-ouverte/igo2-lib/blob/f82944f14f7518174b57143a5fa1db2d0566a59d/packages/integration/src/lib/environment/environment.interface.ts#L27

2024-11-08 21:10 UTC, pelord commented on packages/geo/src/lib/environment/environment.interface.ts
dans AppOptions?

2024-11-08 21:11 UTC, pelord commented
![image](https://github.com/user-attachments/assets/ee42d8fd-7adb-4df5-9c8f-440a8dc3b36a)

2024-11-11 14:04 UTC, pelord reviewed
Voir les commentaires. Plus particulièrement pour l'emplacement de la config du offline: enabled: true/false.

2024-11-11 14:17 UTC, alecarn commented on packages/core/package.json
Il est déjà présent
![image](https://github.com/user-attachments/assets/9e5dd3d4-f09b-43e4-8e0f-dfaf395f66d9)

2024-11-11 15:09 UTC, pelord commented on packages/core/package.json
ok

2024-11-11 15:11 UTC, pelord approved these changes

2024-11-11 15:43 UTC, merged

2024-11-11 15:56 UTC, alecarn commented
:tada: This PR is included in version 18.0.0-next.2 :tada:

The release is available on:
- `v18.0.0-next.2`
- [GitHub release](https://github.com/infra-geo-ouverte/igo2-lib/releases/tag/v18.0.0-next.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2025-02-12 14:58 UTC, alecarn commented
:tada: This PR is included in version 18.0.0 :tada:

The release is available on:
- `v18.0.0`
- [GitHub release](https://github.com/infra-geo-ouverte/igo2-lib/releases/tag/v18.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: