feat(draw): New drawing tool
infra-geo-ouverte/igo2-lib pull request #795
Opened 2020-12-18 17:11 UTC by drekss

Adding new drawing tool to igo2. It allows Point, Linestring, Polygon and Circle geometries to be drawn on the map.

- new "ngx-color-picker": "^9.1.0" dependency in pakage.json
- tool name: "draw"
- need to be add in toolbar and tools to be used

2021-01-07 14:02 UTC, pelord commented
I suggest to change the tool icon. Instead of using the pencil icon, I suggest to use the draw icon.

![image](https://user-images.githubusercontent.com/7397743/103901331-022ab780-50c7-11eb-91f6-bfded0db6b7b.png)

2021-01-14 18:09 UTC, pelord commented on packages/geo/src/lib/draw/draw/draw.component.ts
> +          exportable: false,
You should let the layer being exportable. @drekss

2021-01-14 18:18 UTC, pelord commented on packages/geo/src/lib/draw/draw/draw.component.ts
> +          exportable: false,
But there is an issue with the shapefile output...

2021-01-14 18:56 UTC, pelord commented on packages/geo/src/lib/draw/draw/draw.component.ts
> +          exportable: false,
{"error":true,"msg":"ERROR 1: Attempt to write non-point (POLYGON) geometry to point shapefile.\nERROR 1: Unable to write feature 1 from layer ogr_57d2b442232.\nERROR 1: Terminating translation prematurely after failed\ntranslation of layer ogr_57d2b442232 (use -skipfailures to skip errors)\n"}

2021-01-14 18:57 UTC, pelord commented on packages/geo/src/lib/draw/draw/draw.component.ts
> +          exportable: false,
Maybe split the features on export  by geometry type..
I.E.
if shapefile and multigeometryDraw:
    split by geomety and make a call to ogre for each geometry type.

2021-01-14 20:02 UTC, pelord commented on packages/geo/src/lib/draw/draw/draw.component.ts
> +        console.log(this.store.count$.getValue());
remove this!

2021-01-18 20:16 UTC, mbarbeau requested changes

2021-01-18 20:16 UTC, mbarbeau commented on packages/geo/src/lib/draw/draw/draw.component.html
> +        {{'igo.geo.draw.stroke' | translate}} <mat-icon svgIcon="palette"></mat-icon> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
replace &nbsp  by css

2021-01-18 20:16 UTC, mbarbeau commented on packages/geo/src/lib/draw/draw/draw.component.ts
> +        console.log(this.store.count$.getValue());
:+1:

2021-01-20 18:45 UTC, mbarbeau approved these changes

2021-01-20 18:45 UTC, merged