feat(add-catalog-dialog): add info message if catalog isn't in the pr…
infra-geo-ouverte/igo2-lib pull request #854
Opened 2021-05-12 14:52 UTC by PhilippeLafreniere18

- Before, an error message only displayed to tell the user that the catalog was unavailable

- Now, the add-catalog-dialog stay on the page and tell the user to contact the specify email address in the catalog tool config

- If none email address is provided, the same message as before is displayed in the add-catalog-dialog

2021-05-12 16:18 UTC, pelord commented
Maybe a general var could be defined at the app level .. to be use elsewhere.

2021-05-12 16:19 UTC, pelord requested changes

2021-05-12 16:19 UTC, pelord commented on packages/geo/src/lib/catalog/catalog-library/add-catalog-dialog.component.ts
> +    this.emailAddress = this.configService.getConfig('catalog.emailAddress');
Maybe a general var could be defined at the app level .. to be use elsewhere.

2021-05-17 12:53 UTC, mbarbeau approved these changes

2021-05-17 12:53 UTC, merged