Keep current context open on direction url share url.
infra-geo-ouverte/igo2-lib pull request #998
Opened 2022-02-24 16:29 UTC by pelord

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
When sharing direction by url. The current context is not transfered. 

**What is the new behavior?**
Pass context to shared url. 

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**

**Other information**:

2022-03-03 18:38 UTC, PhilippeLafreniere18 requested changes

2022-03-03 18:38 UTC, PhilippeLafreniere18 commented on packages/geo/src/lib/directions/directions-buttons/directions-buttons.component.ts
> +    if (this.contextUri) {
Check if authenticated

2022-03-17 17:02 UTC, pelord commented on packages/geo/src/lib/directions/directions-buttons/directions-buttons.component.ts
> +    if (this.contextUri) {
check into integration

2022-03-17 20:07 UTC, PhilippeLafreniere18 approved these changes

2022-03-17 20:07 UTC, PhilippeLafreniere18 approved these changes

2022-03-17 20:07 UTC, merged